USE [master]
GO

/****** Object:  Database [task3]    Script Date: 03/14/2017 23:13:47 ******/
CREATE DATABASE [task3] ON  PRIMARY 
( NAME = N'task3', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL10.SQLEXPRESS\MSSQL\DATA\task3.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'task3_log', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL10.SQLEXPRESS\MSSQL\DATA\task3_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [task3] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [task3].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [task3] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [task3] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [task3] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [task3] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [task3] SET ARITHABORT OFF 
GO

ALTER DATABASE [task3] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [task3] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [task3] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [task3] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [task3] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [task3] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [task3] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [task3] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [task3] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [task3] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [task3] SET  DISABLE_BROKER 
GO

ALTER DATABASE [task3] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [task3] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [task3] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [task3] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [task3] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [task3] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [task3] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [task3] SET  READ_WRITE 
GO

ALTER DATABASE [task3] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [task3] SET  MULTI_USER 
GO

ALTER DATABASE [task3] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [task3] SET DB_CHAINING OFF 
GO

