//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Агрегатор_контактов
{
    using System;
    using System.Xml;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// User data.
    /// </summary>
    // *** Start programmer edit section *** (UserDataE CustomAttributes)

    // *** End programmer edit section *** (UserDataE CustomAttributes)
    [ICSSoft.STORMNET.AccessType(ICSSoft.STORMNET.AccessType.none)]
    public class UserDataE : ICSSoft.STORMNET.UI.BaseIndpdEdit
    {
        
        // *** Start programmer edit section *** (UserDataE CustomMembers)

        // *** End programmer edit section *** (UserDataE CustomMembers)

        
        public virtual IIS.Агрегатор_контактов.DPDIUserDataE UserDataEForm
        {
            get
            {
                return ((IIS.Агрегатор_контактов.DPDIUserDataE)(base.Editor));
            }
            set
            {
                base.Editor = ((ICSSoft.STORMNET.UI.IEditor)(value));
            }
        }
        
        public override System.Type GetPrinter(ICSSoft.STORMNET.DataObject[] objects, string contpath, string propertyname)
        {
            // *** Start programmer edit section *** (UserDataE.GetPrinter(DataObject[], string, string) start)

            // *** End programmer edit section *** (UserDataE.GetPrinter(DataObject[], string, string) start)
            throw new ICSSoft.STORMNET.UI.NoSuchContainerException("UserDataE", ICSSoft.STORMNET.UI.EventType.Custom, null, contpath, propertyname);
        }
        
        public override System.Type GetEditor(ICSSoft.STORMNET.UI.EventType eventtype, ICSSoft.STORMNET.DataObject dataobject, string contpath, string propertyname, object tag)
        {
            // *** Start programmer edit section *** (UserDataE.GetEditor(EventType, DataObject, string, string) start)

            // *** End programmer edit section *** (UserDataE.GetEditor(EventType, DataObject, string, string) start)
            throw new ICSSoft.STORMNET.UI.NoSuchContainerException("UserDataE", eventtype, dataobject, contpath, propertyname);
        }
        
        protected override void PrepareDataObjectForEdit(ICSSoft.STORMNET.DataObject dobject)
        {
            // *** Start programmer edit section *** (PrepareDataObjectForEdit (DataObject) start)

            // *** End programmer edit section *** (PrepareDataObjectForEdit (DataObject) start)
            m_objView = ICSSoft.STORMNET.Information.GetView("UserDataE", typeof(IIS.Агрегатор_контактов.UserData));
            if (((dobject.GetStatus(false) != ICSSoft.STORMNET.ObjectStatus.Created) 
                        || dobject.Prototyped))
            {
                ICSSoft.STORMNET.Business.DataServiceProvider.DataService.LoadObject(m_objView, dobject, false, false);
                dobject.InitDataCopy();
            }
            // *** Start programmer edit section *** (PrepareDataObjectForEdit (DataObject) end)

            // *** End programmer edit section *** (PrepareDataObjectForEdit (DataObject) end)
        }
        
        protected override ICSSoft.STORMNET.UI.IEditor GetDpdForm()
        {
            // *** Start programmer edit section *** (UserDataE.GetDpdForm() start)

            // *** End programmer edit section *** (UserDataE.GetDpdForm() start)
            ICSSoft.STORMNET.UI.UniWinEdit form = new ICSSoft.STORMNET.UI.UniWinEdit(new ICSSoft.STORMNET.View[] {
                        ICSSoft.STORMNET.Information.GetView("UserDataE", typeof(IIS.Агрегатор_контактов.UserData))}, "Имзенение данных пользователя", new ICSSoft.STORMNET.UI.EditFormOperations(true, true, false, false));
            // *** Start programmer edit section *** (UserDataE.GetDpdForm() end)

            // *** End programmer edit section *** (UserDataE.GetDpdForm() end)
            return form;
        }
        
        public override Scriptizer.DataObjects.Script GetScript()
        {
            // *** Start programmer edit section *** (UserDataE.GetScript start)

            // *** End programmer edit section *** (UserDataE.GetScript start)
            Scriptizer.DataObjects.Script script = base.GetScript();
            // *** Start programmer edit section *** (UserDataE.GetScript end)

            // *** End programmer edit section *** (UserDataE.GetScript end)
            return script;
        }
        
        protected virtual void prv_AttachEventsFromDpdForm(object form)
        {
            // *** Start programmer edit section *** (prv_AttachEventsFromDpdForm( object form ))

            // *** End programmer edit section *** (prv_AttachEventsFromDpdForm( object form ))
            IIS.Агрегатор_контактов.DPDIUserDataE typedForm = ((IIS.Агрегатор_контактов.DPDIUserDataE)(form));
        }
    }
    
    /// <summary>
    /// User data.
    /// </summary>
    // *** Start programmer edit section *** (DPDIUserDataE CustomAttributes)

    // *** End programmer edit section *** (DPDIUserDataE CustomAttributes)
    public interface DPDIUserDataE
    {
        
        // *** Start programmer edit section *** (DPDIUserDataE CustomMembers)

        // *** End programmer edit section *** (DPDIUserDataE CustomMembers)

        // *** Start programmer edit section *** (DPDIUserDataE Members)

        // *** End programmer edit section *** (DPDIUserDataE Members)

    }
}
