//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeploCorp..TeploUchet
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Район.
    /// </summary>
    // *** Start programmer edit section *** (Район CustomAttributes)

    // *** End programmer edit section *** (Район CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("РайонE", new string[] {
            "Название as \'Название\'"})]
    [View("РайонL", new string[] {
            "Название as \'Название\'"})]
    public class Район : ICSSoft.STORMNET.DataObject
    {
        
        private string fНазвание;
        
        // *** Start programmer edit section *** (Район CustomMembers)

        // *** End programmer edit section *** (Район CustomMembers)

        
        /// <summary>
        /// Название.
        /// </summary>
        // *** Start programmer edit section *** (Район.Название CustomAttributes)

        // *** End programmer edit section *** (Район.Название CustomAttributes)
        [StrLen(255)]
        [NotNull()]
        public virtual string Название
        {
            get
            {
                // *** Start programmer edit section *** (Район.Название Get start)

                // *** End programmer edit section *** (Район.Название Get start)
                string result = this.fНазвание;
                // *** Start programmer edit section *** (Район.Название Get end)

                // *** End programmer edit section *** (Район.Название Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Район.Название Set start)

                // *** End programmer edit section *** (Район.Название Set start)
                this.fНазвание = value;
                // *** Start programmer edit section *** (Район.Название Set end)

                // *** End programmer edit section *** (Район.Название Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "РайонE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View РайонE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("РайонE", typeof(TeploCorp..TeploUchet.Район));
                }
            }
            
            /// <summary>
            /// "РайонL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View РайонL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("РайонL", typeof(TeploCorp..TeploUchet.Район));
                }
            }
        }
    }
}
