//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeploCorp..TeploUchet
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Участок сети.
    /// </summary>
    // *** Start programmer edit section *** (УчастокСети CustomAttributes)

    // *** End programmer edit section *** (УчастокСети CustomAttributes)
    [AutoAltered()]
    [Caption("Участок сети")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("УчастокСетиE", new string[] {
            "Номер as \'Номер\'",
            "Теплоизоляция as \'Теплоизоляция\'",
            "ТипМонтажа as \'Тип монтажа\'",
            "ГодПрокладки as \'Год прокладки\'",
            "Объект as \'Объект\'",
            "Объект.Наименование as \'Наименование\'"}, Hidden=new string[] {
            "Объект"})]
    [View("УчастокСетиL", new string[] {
            "Номер as \'Номер\'",
            "Теплоизоляция as \'Теплоизоляция\'",
            "ТипМонтажа as \'Тип монтажа\'",
            "ГодПрокладки as \'Год прокладки\'",
            "Объект.Наименование as \'Наименование\'"})]
    public class УчастокСети : ICSSoft.STORMNET.DataObject
    {
        
        private int fНомер;
        
        private string fТеплоизоляция;
        
        private string fТипМонтажа;
        
        private System.DateTime fГодПрокладки;
        
        private TeploCorp..TeploUchet.Объект fОбъект;
        
        // *** Start programmer edit section *** (УчастокСети CustomMembers)

        // *** End programmer edit section *** (УчастокСети CustomMembers)

        
        /// <summary>
        /// Номер.
        /// </summary>
        // *** Start programmer edit section *** (УчастокСети.Номер CustomAttributes)

        // *** End programmer edit section *** (УчастокСети.Номер CustomAttributes)
        [NotNull()]
        public virtual int Номер
        {
            get
            {
                // *** Start programmer edit section *** (УчастокСети.Номер Get start)

                // *** End programmer edit section *** (УчастокСети.Номер Get start)
                int result = this.fНомер;
                // *** Start programmer edit section *** (УчастокСети.Номер Get end)

                // *** End programmer edit section *** (УчастокСети.Номер Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (УчастокСети.Номер Set start)

                // *** End programmer edit section *** (УчастокСети.Номер Set start)
                this.fНомер = value;
                // *** Start programmer edit section *** (УчастокСети.Номер Set end)

                // *** End programmer edit section *** (УчастокСети.Номер Set end)
            }
        }
        
        /// <summary>
        /// Теплоизоляция.
        /// </summary>
        // *** Start programmer edit section *** (УчастокСети.Теплоизоляция CustomAttributes)

        // *** End programmer edit section *** (УчастокСети.Теплоизоляция CustomAttributes)
        [StrLen(255)]
        [NotNull()]
        public virtual string Теплоизоляция
        {
            get
            {
                // *** Start programmer edit section *** (УчастокСети.Теплоизоляция Get start)

                // *** End programmer edit section *** (УчастокСети.Теплоизоляция Get start)
                string result = this.fТеплоизоляция;
                // *** Start programmer edit section *** (УчастокСети.Теплоизоляция Get end)

                // *** End programmer edit section *** (УчастокСети.Теплоизоляция Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (УчастокСети.Теплоизоляция Set start)

                // *** End programmer edit section *** (УчастокСети.Теплоизоляция Set start)
                this.fТеплоизоляция = value;
                // *** Start programmer edit section *** (УчастокСети.Теплоизоляция Set end)

                // *** End programmer edit section *** (УчастокСети.Теплоизоляция Set end)
            }
        }
        
        /// <summary>
        /// ТипМонтажа.
        /// </summary>
        // *** Start programmer edit section *** (УчастокСети.ТипМонтажа CustomAttributes)

        // *** End programmer edit section *** (УчастокСети.ТипМонтажа CustomAttributes)
        [StrLen(255)]
        [NotNull()]
        public virtual string ТипМонтажа
        {
            get
            {
                // *** Start programmer edit section *** (УчастокСети.ТипМонтажа Get start)

                // *** End programmer edit section *** (УчастокСети.ТипМонтажа Get start)
                string result = this.fТипМонтажа;
                // *** Start programmer edit section *** (УчастокСети.ТипМонтажа Get end)

                // *** End programmer edit section *** (УчастокСети.ТипМонтажа Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (УчастокСети.ТипМонтажа Set start)

                // *** End programmer edit section *** (УчастокСети.ТипМонтажа Set start)
                this.fТипМонтажа = value;
                // *** Start programmer edit section *** (УчастокСети.ТипМонтажа Set end)

                // *** End programmer edit section *** (УчастокСети.ТипМонтажа Set end)
            }
        }
        
        /// <summary>
        /// ГодПрокладки.
        /// </summary>
        // *** Start programmer edit section *** (УчастокСети.ГодПрокладки CustomAttributes)

        // *** End programmer edit section *** (УчастокСети.ГодПрокладки CustomAttributes)
        [NotNull()]
        public virtual System.DateTime ГодПрокладки
        {
            get
            {
                // *** Start programmer edit section *** (УчастокСети.ГодПрокладки Get start)

                // *** End programmer edit section *** (УчастокСети.ГодПрокладки Get start)
                System.DateTime result = this.fГодПрокладки;
                // *** Start programmer edit section *** (УчастокСети.ГодПрокладки Get end)

                // *** End programmer edit section *** (УчастокСети.ГодПрокладки Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (УчастокСети.ГодПрокладки Set start)

                // *** End programmer edit section *** (УчастокСети.ГодПрокладки Set start)
                this.fГодПрокладки = value;
                // *** Start programmer edit section *** (УчастокСети.ГодПрокладки Set end)

                // *** End programmer edit section *** (УчастокСети.ГодПрокладки Set end)
            }
        }
        
        /// <summary>
        /// Участок сети.
        /// </summary>
        // *** Start programmer edit section *** (УчастокСети.Объект CustomAttributes)

        // *** End programmer edit section *** (УчастокСети.Объект CustomAttributes)
        [PropertyStorage(new string[] {
                "Объект"})]
        public virtual TeploCorp..TeploUchet.Объект Объект
        {
            get
            {
                // *** Start programmer edit section *** (УчастокСети.Объект Get start)

                // *** End programmer edit section *** (УчастокСети.Объект Get start)
                TeploCorp..TeploUchet.Объект result = this.fОбъект;
                // *** Start programmer edit section *** (УчастокСети.Объект Get end)

                // *** End programmer edit section *** (УчастокСети.Объект Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (УчастокСети.Объект Set start)

                // *** End programmer edit section *** (УчастокСети.Объект Set start)
                this.fОбъект = value;
                // *** Start programmer edit section *** (УчастокСети.Объект Set end)

                // *** End programmer edit section *** (УчастокСети.Объект Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "УчастокСетиE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View УчастокСетиE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("УчастокСетиE", typeof(TeploCorp..TeploUchet.УчастокСети));
                }
            }
            
            /// <summary>
            /// "УчастокСетиL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View УчастокСетиL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("УчастокСетиL", typeof(TeploCorp..TeploUchet.УчастокСети));
                }
            }
        }
    }
}
