//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeploCorp.TeploUchet
{
    using System;
    using System.Xml;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Значения монтажа.
    /// </summary>
    // *** Start programmer edit section *** (ЗначенияМонтажа CustomAttributes)

    // *** End programmer edit section *** (ЗначенияМонтажа CustomAttributes)
    public enum ЗначенияМонтажа
    {
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (ЗначенияМонтажа.Надземный CustomAttributes)

        // *** End programmer edit section *** (ЗначенияМонтажа.Надземный CustomAttributes)
        Надземный,
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (ЗначенияМонтажа.Подземный CustomAttributes)

        // *** End programmer edit section *** (ЗначенияМонтажа.Подземный CustomAttributes)
        Подземный,
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (ЗначенияМонтажа.ПоПодвалу CustomAttributes)

        // *** End programmer edit section *** (ЗначенияМонтажа.ПоПодвалу CustomAttributes)
        ПоПодвалу,
    }
}
