//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.BusinessCalendar
{
    using System;
    using System.Xml;


    // *** Start programmer edit section *** (Using statements)
    using ICSSoft.STORMNET;
    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Recurrence type.
    /// </summary>
    // *** Start programmer edit section *** (RecurrenceType CustomAttributes)

    // *** End programmer edit section *** (RecurrenceType CustomAttributes)
    public enum RecurrenceType
    {
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (RecurrenceType.Daily CustomAttributes)
        [Caption("Ежедневно")]
        // *** End programmer edit section *** (RecurrenceType.Daily CustomAttributes)
        Daily,
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (RecurrenceType.Weekly CustomAttributes)
        [Caption("Еженедельно")]
        // *** End programmer edit section *** (RecurrenceType.Weekly CustomAttributes)
        Weekly,
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (RecurrenceType.Monthly CustomAttributes)
        [Caption("Ежемесячно")]
        // *** End programmer edit section *** (RecurrenceType.Monthly CustomAttributes)
        Monthly,
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (RecurrenceType.Yearly CustomAttributes)
        [Caption("Ежегодно")]
        // *** End programmer edit section *** (RecurrenceType.Yearly CustomAttributes)
        Yearly,
    }
}
