//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Product_58826
{
    using System;
    using System.Xml;
    
    
    // *** Start programmer edit section *** (Using statements)
    using ICSSoft.STORMNET.Business;
    using System.Linq;
    using ICSSoft.STORMNET.Business.LINQProvider;
    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// СеместрБС.
    /// </summary>
    // *** Start programmer edit section *** (СеместрБС CustomAttributes)

    // *** End programmer edit section *** (СеместрБС CustomAttributes)
    [ICSSoft.STORMNET.AccessType(ICSSoft.STORMNET.AccessType.none)]
    public class СеместрБС : ICSSoft.STORMNET.Business.BusinessServer
    {
        
        // *** Start programmer edit section *** (СеместрБС CustomMembers)

        // *** End programmer edit section *** (СеместрБС CustomMembers)

        
        // *** Start programmer edit section *** (OnUpdateСеместр CustomAttributes)

        // *** End programmer edit section *** (OnUpdateСеместр CustomAttributes)
        public virtual ICSSoft.STORMNET.DataObject[] OnUpdateСеместр(IIS.Product_58826.Семестр UpdatedObject)
        {
            // *** Start programmer edit section *** (OnUpdateСеместр)
            if (UpdatedObject.GetStatus() == ICSSoft.STORMNET.ObjectStatus.Deleted)
            {
                DataService.LoadObject(UpdatedObject);
                UpdatedObject.SetStatus(ICSSoft.STORMNET.ObjectStatus.Altered);
                UpdatedObject.Актуальность = false;
                var approve = ((SQLDataService)DataService).Query<Модуль>(Модуль.Views.МодульE).Where(k => k.Семестр.__PrimaryKey == UpdatedObject.__PrimaryKey).ToArray();

                foreach (var app in approve)
                {
                    app.SetStatus(ICSSoft.STORMNET.ObjectStatus.Deleted);
                }

                return approve;
            }
            return new ICSSoft.STORMNET.DataObject[0];
            // *** End programmer edit section *** (OnUpdateСеместр)
        }
    }
}
