//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Product_37352
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Contact network.
    /// </summary>
    // *** Start programmer edit section *** (ContactNetwork CustomAttributes)

    // *** End programmer edit section *** (ContactNetwork CustomAttributes)
    [AutoAltered()]
    [Caption("Таблица контактов")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ContactNetworkE", new string[] {
            "Network as \'Сеть\' on \'-Сеть\'",
            "Network.name as \'Название сети\' on \'-Сеть\'",
            "Contact as \'Контакт\' on \'-Контакт\'",
            "Contact.contactName as \'Имя контакта\' on \'-Контакт\'"})]
    [View("ContactNetworkL", new string[] {
            "Network.name as \'\' on \'-Сеть\'",
            "Network as \'\' on \'-Сеть\'",
            "Contact.contactName as \'\' on \'-Контакт\'",
            "Contact as \'\' on \'-Контакт\'"})]
    public class ContactNetwork : ICSSoft.STORMNET.DataObject
    {
        
        private IIS.Product_37352.Network fNetwork;
        
        private IIS.Product_37352.Contact fContact;
        
        // *** Start programmer edit section *** (ContactNetwork CustomMembers)

        // *** End programmer edit section *** (ContactNetwork CustomMembers)

        
        /// <summary>
        /// Contact network.
        /// </summary>
        // *** Start programmer edit section *** (ContactNetwork.Network CustomAttributes)

        // *** End programmer edit section *** (ContactNetwork.Network CustomAttributes)
        [PropertyStorage(new string[] {
                "Network"})]
        [NotNull()]
        public virtual IIS.Product_37352.Network Network
        {
            get
            {
                // *** Start programmer edit section *** (ContactNetwork.Network Get start)

                // *** End programmer edit section *** (ContactNetwork.Network Get start)
                IIS.Product_37352.Network result = this.fNetwork;
                // *** Start programmer edit section *** (ContactNetwork.Network Get end)

                // *** End programmer edit section *** (ContactNetwork.Network Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ContactNetwork.Network Set start)

                // *** End programmer edit section *** (ContactNetwork.Network Set start)
                this.fNetwork = value;
                // *** Start programmer edit section *** (ContactNetwork.Network Set end)

                // *** End programmer edit section *** (ContactNetwork.Network Set end)
            }
        }
        
        /// <summary>
        /// Contact network.
        /// </summary>
        // *** Start programmer edit section *** (ContactNetwork.Contact CustomAttributes)

        // *** End programmer edit section *** (ContactNetwork.Contact CustomAttributes)
        [PropertyStorage(new string[] {
                "Contact"})]
        [NotNull()]
        public virtual IIS.Product_37352.Contact Contact
        {
            get
            {
                // *** Start programmer edit section *** (ContactNetwork.Contact Get start)

                // *** End programmer edit section *** (ContactNetwork.Contact Get start)
                IIS.Product_37352.Contact result = this.fContact;
                // *** Start programmer edit section *** (ContactNetwork.Contact Get end)

                // *** End programmer edit section *** (ContactNetwork.Contact Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ContactNetwork.Contact Set start)

                // *** End programmer edit section *** (ContactNetwork.Contact Set start)
                this.fContact = value;
                // *** Start programmer edit section *** (ContactNetwork.Contact Set end)

                // *** End programmer edit section *** (ContactNetwork.Contact Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ContactNetworkE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ContactNetworkE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ContactNetworkE", typeof(IIS.Product_37352.ContactNetwork));
                }
            }
            
            /// <summary>
            /// "ContactNetworkL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ContactNetworkL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ContactNetworkL", typeof(IIS.Product_37352.ContactNetwork));
                }
            }
        }
    }
}
