//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewPlatform.RecordBookBL
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET.Business;
    using ICSSoft.STORMNET;
    using ICSSoft.STORMNET.Business.Audit;
    using ICSSoft.STORMNET.Business.Audit.Objects;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Оценка.
    /// </summary>
    // *** Start programmer edit section *** (Оценка CustomAttributes)

    // *** End programmer edit section *** (Оценка CustomAttributes)
    [BusinessServer("NewPlatform.RecordBookBL.ЭлектроннаяЗачётка, RecordBookBL(BusinessServers)", ICSSoft.STORMNET.Business.DataServiceObjectEvents.OnAllEvents)]
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.@this)]
    [View("AuditView", new string[] {
            "Значение as \'Значение\'",
            "Дата as \'Дата\'",
            "Состояние as \'Состояние\'",
            "Студент as \'Студент\'",
            "Студент.НомерЗачетки as \'Номер зачетки\'"}, Hidden=new string[] {
            "Студент.НомерЗачетки"})]
    [MasterViewDefineAttribute("AuditView", "Студент", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "НомерЗачетки")]
    [View("ОценкаE", new string[] {
            "Значение as \'Значение\'",
            "Состояние",
            "Дата as \'Дата\'",
            "Студент as \'Студент\'",
            "Студент.ФИО",
            "Студент.Фамилия as \'Фамилия\'",
            "Студент.Имя",
            "Студент.Отчество",
            "Предмет",
            "Предмет.Семестр",
            "Предмет.Семестр.Название",
            "Предмет.Дисциплина",
            "Предмет.Дисциплина.Название"}, Hidden=new string[] {
            "Студент.ФИО",
            "Студент.Фамилия",
            "Студент.Имя",
            "Студент.Отчество",
            "Предмет",
            "Предмет.Семестр",
            "Предмет.Семестр.Название",
            "Предмет.Дисциплина",
            "Предмет.Дисциплина.Название"})]
    [MasterViewDefineAttribute("ОценкаE", "Студент", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "ФИО")]
    public class Оценка : ICSSoft.STORMNET.DataObject, IDataObjectWithAuditFields
    {
        
        private NewPlatform.RecordBookBL.ЗначениеОценки fЗначение;
        
        private System.DateTime fДата;
        
        private NewPlatform.RecordBookBL.СостояниеОценки fСостояние;
        
        private System.Nullable<System.DateTime> fCreateTime;
        
        private string fCreator;
        
        private System.Nullable<System.DateTime> fEditTime;
        
        private string fEditor;
        
        private NewPlatform.RecordBookBL.Студент fСтудент;
        
        private NewPlatform.RecordBookBL.Предмет fПредмет;
        
        // *** Start programmer edit section *** (Оценка CustomMembers)

        // *** End programmer edit section *** (Оценка CustomMembers)

        
        /// <summary>
        /// Значение.
        /// </summary>
        // *** Start programmer edit section *** (Оценка.Значение CustomAttributes)

        // *** End programmer edit section *** (Оценка.Значение CustomAttributes)
        public virtual NewPlatform.RecordBookBL.ЗначениеОценки Значение
        {
            get
            {
                // *** Start programmer edit section *** (Оценка.Значение Get start)

                // *** End programmer edit section *** (Оценка.Значение Get start)
                NewPlatform.RecordBookBL.ЗначениеОценки result = this.fЗначение;
                // *** Start programmer edit section *** (Оценка.Значение Get end)

                // *** End programmer edit section *** (Оценка.Значение Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Оценка.Значение Set start)

                // *** End programmer edit section *** (Оценка.Значение Set start)
                this.fЗначение = value;
                // *** Start programmer edit section *** (Оценка.Значение Set end)

                // *** End programmer edit section *** (Оценка.Значение Set end)
            }
        }
        
        /// <summary>
        /// Дата.
        /// </summary>
        // *** Start programmer edit section *** (Оценка.Дата CustomAttributes)

        // *** End programmer edit section *** (Оценка.Дата CustomAttributes)
        public virtual System.DateTime Дата
        {
            get
            {
                // *** Start programmer edit section *** (Оценка.Дата Get start)

                // *** End programmer edit section *** (Оценка.Дата Get start)
                System.DateTime result = this.fДата;
                // *** Start programmer edit section *** (Оценка.Дата Get end)

                // *** End programmer edit section *** (Оценка.Дата Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Оценка.Дата Set start)

                // *** End programmer edit section *** (Оценка.Дата Set start)
                this.fДата = value;
                // *** Start programmer edit section *** (Оценка.Дата Set end)

                // *** End programmer edit section *** (Оценка.Дата Set end)
            }
        }
        
        /// <summary>
        /// Состояние.
        /// </summary>
        // *** Start programmer edit section *** (Оценка.Состояние CustomAttributes)

        // *** End programmer edit section *** (Оценка.Состояние CustomAttributes)
        public virtual NewPlatform.RecordBookBL.СостояниеОценки Состояние
        {
            get
            {
                // *** Start programmer edit section *** (Оценка.Состояние Get start)

                // *** End programmer edit section *** (Оценка.Состояние Get start)
                NewPlatform.RecordBookBL.СостояниеОценки result = this.fСостояние;
                // *** Start programmer edit section *** (Оценка.Состояние Get end)

                // *** End programmer edit section *** (Оценка.Состояние Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Оценка.Состояние Set start)

                // *** End programmer edit section *** (Оценка.Состояние Set start)
                this.fСостояние = value;
                // *** Start programmer edit section *** (Оценка.Состояние Set end)

                // *** End programmer edit section *** (Оценка.Состояние Set end)
            }
        }
        
        /// <summary>
        /// Время создания объекта.
        /// </summary>
        // *** Start programmer edit section *** (Оценка.CreateTime CustomAttributes)

        // *** End programmer edit section *** (Оценка.CreateTime CustomAttributes)
        public virtual System.Nullable<System.DateTime> CreateTime
        {
            get
            {
                // *** Start programmer edit section *** (Оценка.CreateTime Get start)

                // *** End programmer edit section *** (Оценка.CreateTime Get start)
                System.Nullable<System.DateTime> result = this.fCreateTime;
                // *** Start programmer edit section *** (Оценка.CreateTime Get end)

                // *** End programmer edit section *** (Оценка.CreateTime Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Оценка.CreateTime Set start)

                // *** End programmer edit section *** (Оценка.CreateTime Set start)
                this.fCreateTime = value;
                // *** Start programmer edit section *** (Оценка.CreateTime Set end)

                // *** End programmer edit section *** (Оценка.CreateTime Set end)
            }
        }
        
        /// <summary>
        /// Создатель объекта.
        /// </summary>
        // *** Start programmer edit section *** (Оценка.Creator CustomAttributes)

        // *** End programmer edit section *** (Оценка.Creator CustomAttributes)
        [StrLen(255)]
        public virtual string Creator
        {
            get
            {
                // *** Start programmer edit section *** (Оценка.Creator Get start)

                // *** End programmer edit section *** (Оценка.Creator Get start)
                string result = this.fCreator;
                // *** Start programmer edit section *** (Оценка.Creator Get end)

                // *** End programmer edit section *** (Оценка.Creator Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Оценка.Creator Set start)

                // *** End programmer edit section *** (Оценка.Creator Set start)
                this.fCreator = value;
                // *** Start programmer edit section *** (Оценка.Creator Set end)

                // *** End programmer edit section *** (Оценка.Creator Set end)
            }
        }
        
        /// <summary>
        /// Время последнего редактирования объекта.
        /// </summary>
        // *** Start programmer edit section *** (Оценка.EditTime CustomAttributes)

        // *** End programmer edit section *** (Оценка.EditTime CustomAttributes)
        public virtual System.Nullable<System.DateTime> EditTime
        {
            get
            {
                // *** Start programmer edit section *** (Оценка.EditTime Get start)

                // *** End programmer edit section *** (Оценка.EditTime Get start)
                System.Nullable<System.DateTime> result = this.fEditTime;
                // *** Start programmer edit section *** (Оценка.EditTime Get end)

                // *** End programmer edit section *** (Оценка.EditTime Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Оценка.EditTime Set start)

                // *** End programmer edit section *** (Оценка.EditTime Set start)
                this.fEditTime = value;
                // *** Start programmer edit section *** (Оценка.EditTime Set end)

                // *** End programmer edit section *** (Оценка.EditTime Set end)
            }
        }
        
        /// <summary>
        /// Последний редактор объекта.
        /// </summary>
        // *** Start programmer edit section *** (Оценка.Editor CustomAttributes)

        // *** End programmer edit section *** (Оценка.Editor CustomAttributes)
        [StrLen(255)]
        public virtual string Editor
        {
            get
            {
                // *** Start programmer edit section *** (Оценка.Editor Get start)

                // *** End programmer edit section *** (Оценка.Editor Get start)
                string result = this.fEditor;
                // *** Start programmer edit section *** (Оценка.Editor Get end)

                // *** End programmer edit section *** (Оценка.Editor Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Оценка.Editor Set start)

                // *** End programmer edit section *** (Оценка.Editor Set start)
                this.fEditor = value;
                // *** Start programmer edit section *** (Оценка.Editor Set end)

                // *** End programmer edit section *** (Оценка.Editor Set end)
            }
        }
        
        /// <summary>
        /// Оценка.
        /// </summary>
        // *** Start programmer edit section *** (Оценка.Студент CustomAttributes)

        // *** End programmer edit section *** (Оценка.Студент CustomAttributes)
        [PropertyStorage(new string[] {
                "Студент"})]
        [NotNull()]
        public virtual NewPlatform.RecordBookBL.Студент Студент
        {
            get
            {
                // *** Start programmer edit section *** (Оценка.Студент Get start)

                // *** End programmer edit section *** (Оценка.Студент Get start)
                NewPlatform.RecordBookBL.Студент result = this.fСтудент;
                // *** Start programmer edit section *** (Оценка.Студент Get end)

                // *** End programmer edit section *** (Оценка.Студент Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Оценка.Студент Set start)

                // *** End programmer edit section *** (Оценка.Студент Set start)
                this.fСтудент = value;
                // *** Start programmer edit section *** (Оценка.Студент Set end)

                // *** End programmer edit section *** (Оценка.Студент Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку NewPlatform.RecordBookBL.Предмет.
        /// </summary>
        // *** Start programmer edit section *** (Оценка.Предмет CustomAttributes)

        // *** End programmer edit section *** (Оценка.Предмет CustomAttributes)
        [Agregator()]
        [NotNull()]
        public virtual NewPlatform.RecordBookBL.Предмет Предмет
        {
            get
            {
                // *** Start programmer edit section *** (Оценка.Предмет Get start)

                // *** End programmer edit section *** (Оценка.Предмет Get start)
                NewPlatform.RecordBookBL.Предмет result = this.fПредмет;
                // *** Start programmer edit section *** (Оценка.Предмет Get end)

                // *** End programmer edit section *** (Оценка.Предмет Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Оценка.Предмет Set start)

                // *** End programmer edit section *** (Оценка.Предмет Set start)
                this.fПредмет = value;
                // *** Start programmer edit section *** (Оценка.Предмет Set end)

                // *** End programmer edit section *** (Оценка.Предмет Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "AuditView" view.
            /// </summary>
            public static ICSSoft.STORMNET.View AuditView
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("AuditView", typeof(NewPlatform.RecordBookBL.Оценка));
                }
            }
            
            /// <summary>
            /// "ОценкаE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ОценкаE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ОценкаE", typeof(NewPlatform.RecordBookBL.Оценка));
                }
            }
        }
        
        /// <summary>
        /// Audit class settings.
        /// </summary>
        public class AuditSettings
        {
            
            /// <summary>
            /// Включён ли аудит для класса.
            /// </summary>
            public static bool AuditEnabled = true;
            
            /// <summary>
            /// Использовать имя представления для аудита по умолчанию.
            /// </summary>
            public static bool UseDefaultView = false;
            
            /// <summary>
            /// Включён ли аудит операции чтения.
            /// </summary>
            public static bool SelectAudit = false;
            
            /// <summary>
            /// Имя представления для аудирования операции чтения.
            /// </summary>
            public static string SelectAuditViewName = "AuditView";
            
            /// <summary>
            /// Включён ли аудит операции создания.
            /// </summary>
            public static bool InsertAudit = true;
            
            /// <summary>
            /// Имя представления для аудирования операции создания.
            /// </summary>
            public static string InsertAuditViewName = "AuditView";
            
            /// <summary>
            /// Включён ли аудит операции изменения.
            /// </summary>
            public static bool UpdateAudit = false;
            
            /// <summary>
            /// Имя представления для аудирования операции изменения.
            /// </summary>
            public static string UpdateAuditViewName = "AuditView";
            
            /// <summary>
            /// Включён ли аудит операции удаления.
            /// </summary>
            public static bool DeleteAudit = true;
            
            /// <summary>
            /// Имя представления для аудирования операции удаления.
            /// </summary>
            public static string DeleteAuditViewName = "AuditView";
            
            /// <summary>
            /// Путь к форме просмотра результатов аудита.
            /// </summary>
            public static string FormUrl = "";
            
            /// <summary>
            /// Режим записи данных аудита (синхронный или асинхронный).
            /// </summary>
            public static ICSSoft.STORMNET.Business.Audit.Objects.tWriteMode WriteMode = ICSSoft.STORMNET.Business.Audit.Objects.tWriteMode.Synchronous;
            
            /// <summary>
            /// Максимальная длина сохраняемого значения поля (если 0, то строка обрезаться не будет).
            /// </summary>
            public static int PrunningLength = 0;
            
            /// <summary>
            /// Показывать ли пользователям в изменениях первичные ключи.
            /// </summary>
            public static bool ShowPrimaryKey = false;
            
            /// <summary>
            /// Сохранять ли старое значение.
            /// </summary>
            public static bool KeepOldValue = true;
            
            /// <summary>
            /// Сжимать ли сохраняемые значения.
            /// </summary>
            public static bool Compress = false;
            
            /// <summary>
            /// Сохранять ли все значения атрибутов, а не только изменяемые.
            /// </summary>
            public static bool KeepAllValues = false;
        }
    }
    
    /// <summary>
    /// Detail array of Оценка.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfОценка CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfОценка CustomAttributes)
    public class DetailArrayOfОценка : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (NewPlatform.RecordBookBL.DetailArrayOfОценка members)

        // *** End programmer edit section *** (NewPlatform.RecordBookBL.DetailArrayOfОценка members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type Оценка by index.
        /// </summary>
        /// <summary>
        /// Adds object with type Оценка.
        /// </summary>
        public DetailArrayOfОценка(NewPlatform.RecordBookBL.Предмет fПредмет) : 
                base(typeof(Оценка), ((ICSSoft.STORMNET.DataObject)(fПредмет)))
        {
        }
        
        public NewPlatform.RecordBookBL.Оценка this[int index]
        {
            get
            {
                return ((NewPlatform.RecordBookBL.Оценка)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(NewPlatform.RecordBookBL.Оценка dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
