//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewPlatform.RecordBookBL
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    using ICSSoft.STORMNET.Business.Audit;
    using ICSSoft.STORMNET.Business.Audit.Objects;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Факультет.
    /// </summary>
    // *** Start programmer edit section *** (Факультет CustomAttributes)

    // *** End programmer edit section *** (Факультет CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("AuditView", new string[] {
            "Название as \'Название\'"})]
    [AssociatedDetailViewAttribute("AuditView", "Специальности", "AuditView", true, "", "Специальности", true, new string[] {
            ""})]
    [View("ФакультетE", new string[] {
            "Название as \'Название\'"})]
    [AssociatedDetailViewAttribute("ФакультетE", "Специальности", "СпециальностьE", true, "", "Специальности", true, new string[] {
            ""})]
    [View("ФакультетL", new string[] {
            "Название as \'Название\'"})]
    public class Факультет : ICSSoft.STORMNET.DataObject, IDataObjectWithAuditFields
    {
        
        private string fНазвание;
        
        private System.Nullable<System.DateTime> fCreateTime;
        
        private string fCreator;
        
        private System.Nullable<System.DateTime> fEditTime;
        
        private string fEditor;
        
        private NewPlatform.RecordBookBL.DetailArrayOfСпециальность fСпециальности;
        
        // *** Start programmer edit section *** (Факультет CustomMembers)

        // *** End programmer edit section *** (Факультет CustomMembers)

        
        /// <summary>
        /// Название.
        /// </summary>
        // *** Start programmer edit section *** (Факультет.Название CustomAttributes)

        // *** End programmer edit section *** (Факультет.Название CustomAttributes)
        [StrLen(255)]
        public virtual string Название
        {
            get
            {
                // *** Start programmer edit section *** (Факультет.Название Get start)

                // *** End programmer edit section *** (Факультет.Название Get start)
                string result = this.fНазвание;
                // *** Start programmer edit section *** (Факультет.Название Get end)

                // *** End programmer edit section *** (Факультет.Название Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Факультет.Название Set start)

                // *** End programmer edit section *** (Факультет.Название Set start)
                this.fНазвание = value;
                // *** Start programmer edit section *** (Факультет.Название Set end)

                // *** End programmer edit section *** (Факультет.Название Set end)
            }
        }
        
        /// <summary>
        /// Время создания объекта.
        /// </summary>
        // *** Start programmer edit section *** (Факультет.CreateTime CustomAttributes)

        // *** End programmer edit section *** (Факультет.CreateTime CustomAttributes)
        public virtual System.Nullable<System.DateTime> CreateTime
        {
            get
            {
                // *** Start programmer edit section *** (Факультет.CreateTime Get start)

                // *** End programmer edit section *** (Факультет.CreateTime Get start)
                System.Nullable<System.DateTime> result = this.fCreateTime;
                // *** Start programmer edit section *** (Факультет.CreateTime Get end)

                // *** End programmer edit section *** (Факультет.CreateTime Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Факультет.CreateTime Set start)

                // *** End programmer edit section *** (Факультет.CreateTime Set start)
                this.fCreateTime = value;
                // *** Start programmer edit section *** (Факультет.CreateTime Set end)

                // *** End programmer edit section *** (Факультет.CreateTime Set end)
            }
        }
        
        /// <summary>
        /// Создатель объекта.
        /// </summary>
        // *** Start programmer edit section *** (Факультет.Creator CustomAttributes)

        // *** End programmer edit section *** (Факультет.Creator CustomAttributes)
        [StrLen(255)]
        public virtual string Creator
        {
            get
            {
                // *** Start programmer edit section *** (Факультет.Creator Get start)

                // *** End programmer edit section *** (Факультет.Creator Get start)
                string result = this.fCreator;
                // *** Start programmer edit section *** (Факультет.Creator Get end)

                // *** End programmer edit section *** (Факультет.Creator Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Факультет.Creator Set start)

                // *** End programmer edit section *** (Факультет.Creator Set start)
                this.fCreator = value;
                // *** Start programmer edit section *** (Факультет.Creator Set end)

                // *** End programmer edit section *** (Факультет.Creator Set end)
            }
        }
        
        /// <summary>
        /// Время последнего редактирования объекта.
        /// </summary>
        // *** Start programmer edit section *** (Факультет.EditTime CustomAttributes)

        // *** End programmer edit section *** (Факультет.EditTime CustomAttributes)
        public virtual System.Nullable<System.DateTime> EditTime
        {
            get
            {
                // *** Start programmer edit section *** (Факультет.EditTime Get start)

                // *** End programmer edit section *** (Факультет.EditTime Get start)
                System.Nullable<System.DateTime> result = this.fEditTime;
                // *** Start programmer edit section *** (Факультет.EditTime Get end)

                // *** End programmer edit section *** (Факультет.EditTime Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Факультет.EditTime Set start)

                // *** End programmer edit section *** (Факультет.EditTime Set start)
                this.fEditTime = value;
                // *** Start programmer edit section *** (Факультет.EditTime Set end)

                // *** End programmer edit section *** (Факультет.EditTime Set end)
            }
        }
        
        /// <summary>
        /// Последний редактор объекта.
        /// </summary>
        // *** Start programmer edit section *** (Факультет.Editor CustomAttributes)

        // *** End programmer edit section *** (Факультет.Editor CustomAttributes)
        [StrLen(255)]
        public virtual string Editor
        {
            get
            {
                // *** Start programmer edit section *** (Факультет.Editor Get start)

                // *** End programmer edit section *** (Факультет.Editor Get start)
                string result = this.fEditor;
                // *** Start programmer edit section *** (Факультет.Editor Get end)

                // *** End programmer edit section *** (Факультет.Editor Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Факультет.Editor Set start)

                // *** End programmer edit section *** (Факультет.Editor Set start)
                this.fEditor = value;
                // *** Start programmer edit section *** (Факультет.Editor Set end)

                // *** End programmer edit section *** (Факультет.Editor Set end)
            }
        }
        
        /// <summary>
        /// Факультет.
        /// </summary>
        // *** Start programmer edit section *** (Факультет.Специальности CustomAttributes)

        // *** End programmer edit section *** (Факультет.Специальности CustomAttributes)
        public virtual NewPlatform.RecordBookBL.DetailArrayOfСпециальность Специальности
        {
            get
            {
                // *** Start programmer edit section *** (Факультет.Специальности Get start)

                // *** End programmer edit section *** (Факультет.Специальности Get start)
                if ((this.fСпециальности == null))
                {
                    this.fСпециальности = new NewPlatform.RecordBookBL.DetailArrayOfСпециальность(this);
                }
                NewPlatform.RecordBookBL.DetailArrayOfСпециальность result = this.fСпециальности;
                // *** Start programmer edit section *** (Факультет.Специальности Get end)

                // *** End programmer edit section *** (Факультет.Специальности Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Факультет.Специальности Set start)

                // *** End programmer edit section *** (Факультет.Специальности Set start)
                this.fСпециальности = value;
                // *** Start programmer edit section *** (Факультет.Специальности Set end)

                // *** End programmer edit section *** (Факультет.Специальности Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "AuditView" view.
            /// </summary>
            public static ICSSoft.STORMNET.View AuditView
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("AuditView", typeof(NewPlatform.RecordBookBL.Факультет));
                }
            }
            
            /// <summary>
            /// "ФакультетE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ФакультетE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ФакультетE", typeof(NewPlatform.RecordBookBL.Факультет));
                }
            }
            
            /// <summary>
            /// "ФакультетL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ФакультетL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ФакультетL", typeof(NewPlatform.RecordBookBL.Факультет));
                }
            }
        }
        
        /// <summary>
        /// Audit class settings.
        /// </summary>
        public class AuditSettings
        {
            
            /// <summary>
            /// Включён ли аудит для класса.
            /// </summary>
            public static bool AuditEnabled = true;
            
            /// <summary>
            /// Использовать имя представления для аудита по умолчанию.
            /// </summary>
            public static bool UseDefaultView = false;
            
            /// <summary>
            /// Включён ли аудит операции чтения.
            /// </summary>
            public static bool SelectAudit = false;
            
            /// <summary>
            /// Имя представления для аудирования операции чтения.
            /// </summary>
            public static string SelectAuditViewName = "AuditView";
            
            /// <summary>
            /// Включён ли аудит операции создания.
            /// </summary>
            public static bool InsertAudit = true;
            
            /// <summary>
            /// Имя представления для аудирования операции создания.
            /// </summary>
            public static string InsertAuditViewName = "AuditView";
            
            /// <summary>
            /// Включён ли аудит операции изменения.
            /// </summary>
            public static bool UpdateAudit = false;
            
            /// <summary>
            /// Имя представления для аудирования операции изменения.
            /// </summary>
            public static string UpdateAuditViewName = "AuditView";
            
            /// <summary>
            /// Включён ли аудит операции удаления.
            /// </summary>
            public static bool DeleteAudit = true;
            
            /// <summary>
            /// Имя представления для аудирования операции удаления.
            /// </summary>
            public static string DeleteAuditViewName = "AuditView";
            
            /// <summary>
            /// Путь к форме просмотра результатов аудита.
            /// </summary>
            public static string FormUrl = "";
            
            /// <summary>
            /// Режим записи данных аудита (синхронный или асинхронный).
            /// </summary>
            public static ICSSoft.STORMNET.Business.Audit.Objects.tWriteMode WriteMode = ICSSoft.STORMNET.Business.Audit.Objects.tWriteMode.Synchronous;
            
            /// <summary>
            /// Максимальная длина сохраняемого значения поля (если 0, то строка обрезаться не будет).
            /// </summary>
            public static int PrunningLength = 0;
            
            /// <summary>
            /// Показывать ли пользователям в изменениях первичные ключи.
            /// </summary>
            public static bool ShowPrimaryKey = false;
            
            /// <summary>
            /// Сохранять ли старое значение.
            /// </summary>
            public static bool KeepOldValue = true;
            
            /// <summary>
            /// Сжимать ли сохраняемые значения.
            /// </summary>
            public static bool Compress = false;
            
            /// <summary>
            /// Сохранять ли все значения атрибутов, а не только изменяемые.
            /// </summary>
            public static bool KeepAllValues = false;
        }
    }
}
