/*flexberryautogenerated="false"*/
using System;
using System.Web.UI;

namespace Web
{
    using System;
    using ICSSoft.STORMNET.Web.Controls;

    using Resources;
    using System.Web;
    using ICSSoft.STORMNET.FunctionalLanguage.SQLWhere;
    using ICSSoft.STORMNET.Business;
    using ICSSoft.STORMNET.Business.LINQProvider;
    using System.Linq;
    using ICSSoft.STORMNET.FunctionalLanguage;
    using ICSSoft.STORMNET;
    using TeploCorp.TeploUchet;

    public partial class FindForm : Page
    {
        protected void Page_Load(object sender, EventArgs e)
        {

        }
    }
}
