/*flexberryautogenerated="false"*/
using System;
using System.Data;
using System.Configuration;
using System.Collections;
using System.Web;
using System.Web.Security;
using System.Web.UI;
using System.Web.UI.WebControls;
using System.Web.UI.WebControls.WebParts;
using System.Web.UI.HtmlControls;

using ICSSoft.STORMNET.Business;
using ICSSoft.STORMNET.Business.LINQProvider;

using System.Linq;
using System.Collections.Generic;
using ICSSoft.STORMNET.FunctionalLanguage.SQLWhere;
using ICSSoft.STORMNET.FunctionalLanguage;
using ICSSoft.STORMNET;

namespace IIS.Агрегатор_контактов
{
    public partial class SQLrequests : System.Web.UI.Page
    {
        /*
        1)  Declare @n as int = 1
	        SELECT Top(@n) User_id1, COUNT(User_id1) From dbo.contact  GROUP BY User_id1 

        2)  SELECT TOP 1  surname, COUNT(surname) count  From dbo.profile GROUP BY surname Order By count DESC

        3)  Select  dbo.userBase.id, dbo.profile.name, DATEPART(YEAR, birthday) as userbirthday, gender, network.name, Count(*) as profile_count  FROM dbo.userBase 
	        INNER JOIN dbo.profile
            ON dbo.userBase.id=dbo.profile.User_id	
	        INNER JOIN dbo.network
            ON dbo.profile.network_idnetwork=dbo.network.id
	        group by dbo.userBase.id, dbo.profile.name, DATEPART(YEAR, birthday), gender, network.name
	        ORDER BY profile_count DESC, network.name, userbirthday

        4)  Declare 
		        @contact_count real,
		        @user_count real
	        SELECT @contact_count=Count(user_ID1) From dbo.contact
	        SELECT @user_count=Count(id) From dbo.userBase
	        PRINT @contact_count/@user_count

        5)	Declare 
		        @percon_count INT
	        SELECT  @percon_count = COUNT(gender) From dbo.profile
	        SELECT  COUNT(gender)*100/@percon_count From dbo.profile  Where gender='m' GROUP BY gender	
	        SELECT  COUNT(gender)*100/@percon_count From dbo.profile  Where gender='f' GROUP BY gender
	    */
        protected void Page_Load(object sender, EventArgs e)
        {

        }

        protected void Button1_Click(object sender, EventArgs e)
        {
            int n = Convert.ToInt32(TextBox1.Text);
            var ds = (SQLDataService)DataServiceProvider.DataService; // Cервис данных.

            List<Contact> contact = ds.Query<Contact>(Contact.Views.ContactE).ToList<Contact>(); // Получение объекта.

            //List<Contact> per = contact.GroupBy(o => o.contactName);

            //IQueryable<Contact> objs = ds.Query<Contact>(Contact.Views.ContactE);

            //IQueryable<Contact> per = from o in objs group o by o.MyUserData into grouping orderby o.MyUserData select o.MyUserData;

            //IQueryable<Contact> objs1 = from o in objs select o;

            //Contact contact = ds.Query<Contact>(Contact.Views.ContactE).Where(o => o.contactName == "Пользователь 1").OrderBy(o => o.contactName).FirstOrDefault();

            //Contact contact1 = ds.Query<Contact>(Contact.Views.ContactE).Where(o => o.contactName == "Пользователь 1").OrderBy(o => o.contactName).FirstOrDefault();

            //IQueryable<Contact> per = contact

            ListBox1.Items.Clear();
            /*for (int i = 0; i < contact.Count; i++)
                ListBox1.Items.Add(contact[i].contactName);*/
        }

        protected void Button2_Click(object sender, EventArgs e)
        {
            var ds = (SQLDataService)DataServiceProvider.DataService; // Cервис данных.
            List<Profile> profile = ds.Query<Profile>(Profile.Views.ProfileE).ToList<Profile>(); // Получение объекта.
            ListBox2.Items.Clear();
            for (int i = 0; i < profile.Count; i++)
                ListBox2.Items.Add(profile[i].name);
        }

        protected void Button3_Click(object sender, EventArgs e)
        {
            var ds = (SQLDataService)DataServiceProvider.DataService; // Cервис данных.
            List<Profile> profile = ds.Query<Profile>(Profile.Views.ProfileE).ToList<Profile>(); // Получение объекта.
            ListBox3.Items.Clear();
            for (int i = 0; i < profile.Count; i++)
                ListBox3.Items.Add(profile[i].name);
        }

        protected void Button4_Click(object sender, EventArgs e)
        {
            LoadingCustomizationStruct lcs = LoadingCustomizationStruct.GetSimpleStruct(typeof(Contact), "ContactE");
            lcs.View = Contact.Views.ContactE;
            lcs.LoadingTypes = new Type[] { typeof(Contact) };

            var data = DataServiceProvider.DataService.LoadObjects(lcs).Cast<Contact>();
            var profileCount = data.ToList<Contact>().Count;

            Label2.Text = string.Format("Среднее колличество контактов: {0}", profileCount);
        }

        protected void Button5_Click(object sender, EventArgs e)
        {
            LoadingCustomizationStruct lcs = LoadingCustomizationStruct.GetSimpleStruct(typeof(Profile), "ProfileE");
            lcs.View = Profile.Views.ProfileE;
            lcs.LoadingTypes = new Type[] { typeof(Profile) };

            var data = DataServiceProvider.DataService.LoadObjects(lcs).Cast<Profile>();
            var profileCount = data.ToList<Profile>().Count;

            var ld = SQLWhereLanguageDef.LanguageDef;
            lcs.LimitFunction = ld.GetFunction(ld.funcEQ,
                    new VariableDef(ld.StringType, Information.ExtractPropertyPath<Profile>(x => x.gender)), "m");

            data = DataServiceProvider.DataService.LoadObjects(lcs).Cast<Profile>();

            var mCount = data.ToList<Profile>().Count;

            Label3.Text = string.Format("Мужчин = {0}%    Женищин = {1}%", mCount * 100 / profileCount, 100 - mCount * 100 / profileCount);
        }
    }
}
