<%--flexberryautogenerated="true"--%>
<%@ Page Language="C#" MasterPageFile="~/Site1.Master" AutoEventWireup="true" CodeBehind="SQLrequests.aspx.cs" Inherits="IIS.Агрегатор_контактов.SQLrequests" Title="Untitled Page" %>
<asp:Content ID="Content1" ContentPlaceHolderID="PageTitlePlaceholder" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="AddToHeadPlaceholder" runat="server">
</asp:Content>
<asp:Content ID="Content3" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <H4>Запрос 1</H4>
    <H5>Вывести топ N пользователей, имеющих максимальное количество контактов.</H5>
    <div>
        <asp:Label ID="Label1" runat="server" Text="Колличество пользователей" Font-Size="Medium"></asp:Label>
        <asp:TextBox ID="TextBox1" runat="server" MaxLength="2" TextMode="Number">1</asp:TextBox>
        <asp:Button ID="Button1" runat="server" Text="Kill this button" OnClick="Button1_Click" />
        <asp:ListView ID="ListView1" runat="server">
        </asp:ListView>
    </div>
</asp:Content>
<asp:Content ID="Content4" ContentPlaceHolderID="ContentPlaceHolder0" runat="server">
</asp:Content>
