//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Агрегатор_контактов
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Социальная сеть.
    /// </summary>
    // *** Start programmer edit section *** (Network CustomAttributes)

    // *** End programmer edit section *** (Network CustomAttributes)
    [AutoAltered()]
    [Caption("Сайт")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("NetworkE", new string[] {
            "name as \'Имя\'",
            "site as \'Сайт\'"})]
    [View("NetworkL", new string[] {
            "name as \'Имя\'",
            "site as \'Сайт\'"})]
    public class Network : ICSSoft.STORMNET.DataObject
    {
        
        private string fsite;
        
        private string fname;
        
        // *** Start programmer edit section *** (Network CustomMembers)

        // *** End programmer edit section *** (Network CustomMembers)

        
        /// <summary>
        /// site.
        /// </summary>
        // *** Start programmer edit section *** (Network.site CustomAttributes)

        // *** End programmer edit section *** (Network.site CustomAttributes)
        [StrLen(255)]
        public virtual string site
        {
            get
            {
                // *** Start programmer edit section *** (Network.site Get start)

                // *** End programmer edit section *** (Network.site Get start)
                string result = this.fsite;
                // *** Start programmer edit section *** (Network.site Get end)

                // *** End programmer edit section *** (Network.site Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Network.site Set start)

                // *** End programmer edit section *** (Network.site Set start)
                this.fsite = value;
                // *** Start programmer edit section *** (Network.site Set end)

                // *** End programmer edit section *** (Network.site Set end)
            }
        }
        
        /// <summary>
        /// name.
        /// </summary>
        // *** Start programmer edit section *** (Network.name CustomAttributes)

        // *** End programmer edit section *** (Network.name CustomAttributes)
        [StrLen(255)]
        public virtual string name
        {
            get
            {
                // *** Start programmer edit section *** (Network.name Get start)

                // *** End programmer edit section *** (Network.name Get start)
                string result = this.fname;
                // *** Start programmer edit section *** (Network.name Get end)

                // *** End programmer edit section *** (Network.name Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Network.name Set start)

                // *** End programmer edit section *** (Network.name Set start)
                this.fname = value;
                // *** Start programmer edit section *** (Network.name Set end)

                // *** End programmer edit section *** (Network.name Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "NetworkE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View NetworkE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("NetworkE", typeof(IIS.Агрегатор_контактов.Network));
                }
            }
            
            /// <summary>
            /// "NetworkL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View NetworkL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("NetworkL", typeof(IIS.Агрегатор_контактов.Network));
                }
            }
        }
    }
}
