/*flexberryautogenerated="true"*/
namespace IIS.BusinessCalendar
{
    using System;
    using ICSSoft.STORMNET.Web.Controls;

    using Resources;

    public partial class ExceptionDayL : BaseListForm<ExceptionDay>
    {
        /// <summary>
        /// Конструктор без параметров,
        /// инициализирует свойства, соответствующие конкретной форме.
        /// </summary>
        public ExceptionDayL() : base(ExceptionDay.Views.ExceptionDayL)
        {
            EditPage = ExceptionDayE.FormPath;
        }
                
        /// <summary>
        /// Путь до формы.
        /// </summary>
        public static string FormPath
        {
            get { return "~/forms/ExceptionDay/ExceptionDayL.aspx"; }
        }

        /// <summary>
        /// Вызывается самым первым в Page_Load.
        /// </summary>
        protected override void Preload()
        {
            String jsname = "BusinessCalendar";
            String jsJQuery = "JQueryMinJs";
            String jsExcDayForm = "ExcDayForm";

            String jsExcDayFormUrl = "~/shared/script/ExceptionDayForm.js";
            String jsJQueryUrl = "~/shared/script/jquery.min.js";
            String jsurl = "~/shared/script/businessCalendar.js";

            Type jsType = this.GetType();

            System.Web.UI.ClientScriptManager js = Page.ClientScript;

            js.RegisterClientScriptInclude(jsType, jsJQuery, ResolveClientUrl(jsJQueryUrl));
            js.RegisterClientScriptInclude(jsType, jsname, ResolveClientUrl(jsurl));
            js.RegisterClientScriptInclude(jsType, jsExcDayForm, ResolveClientUrl(jsExcDayFormUrl));
            
        }

        /// <summary>
        /// Вызывается самым последним в Page_Load.
        /// </summary>
        protected override void Postload()
        {
            WebObjectListView1.Operations.OpenEditorInNewWindow = true;
            WebObjectListView1.Operations.OpenEditorInModalWindow = true;
        }
    }
}
