<%--flexberryautogenerated="true"--%>
<%@ Page Language="C#" MasterPageFile="~/Site1.Master"  AutoEventWireup="true" CodeBehind="WeekE.aspx.cs" Inherits="IIS.BusinessCalendar.WeekE" %>
<%@ Import namespace="NewPlatform.Flexberry.Web.Page" %>
<%@ Register TagName="TimeSpanView" TagPrefix="ac" Src="~/Controls/TimeSpanView/TimeSpanView.ascx" %>
<%-- Autogenerated section start [Register] --%>
<%-- Autogenerated section end [Register] --%>

<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <div class="<%= Constants.FormCssClass %> <%= Constants.EditFormCssClass %>">
        <h2 class="<%= Constants.FormHeaderCssClass %> <%= Constants.EditFormHeaderCssClass %>">Неделя</h2>
        <div class="<%= Constants.FormToolbarCssClass %> <%= Constants.EditFormToolbarCssClass %> <%= Constants.StickyCssClass %>">
            <asp:ImageButton ID="SaveBtn" runat="server" SkinID="SaveBtn" OnClick="SaveBtn_Click" AlternateText="<%$ Resources: Resource, Save %>" ValidationGroup="savedoc" />
            <asp:ImageButton ID="SaveAndCloseBtn" runat="server" SkinID="SaveAndCloseBtn" OnClick="SaveAndCloseBtn_Click" AlternateText="<%$ Resources: Resource, Save_Close %>" ValidationGroup="savedoc" />
            <asp:ImageButton ID="CancelBtn" runat="server" SkinID="CancelBtn" OnClick="CancelBtn_Click" AlternateText="<%$ Resources: Resource, Cancel %>" />
        </div>
        <div class="<%= Constants.FormControlsCssClass %> <%= Constants.EditFormControlsCssClass %>">
            <%-- Autogenerated section start [Controls] --%>
<!-- autogenerated start -->
            <div>
                <div class="clearfix">
                    <asp:Label CssClass="descLbl" ID="ctrlNameLabel" runat="server" Text="Название недели" EnableViewState="False">
                    </asp:Label>
                    <asp:TextBox CssClass="descTxt" ID="ctrlName" runat="server">
                    </asp:TextBox>

                </div>
                <div class="clearfix">
                    <asp:Label CssClass="descLbl" ID="ctrlIsDefaultLabel" runat="server" Text="Стандартная" EnableViewState="False">
                    </asp:Label>
                    <asp:CheckBox ID="ctrlIsDefault" CssClass="descTxt" runat="server" Text="" />
                </div>
                <div class="clearfix">
                    <asp:Label CssClass="descLbl" ID="ctrlMondayLabel" runat="server" Text="Понедельник" EnableViewState="False">
                    </asp:Label>
                    <ac:TimeSpanView ID="ctrlMondayTS" runat="server" />
                </div>
                <div class="clearfix">
                    <asp:Label CssClass="descLbl" ID="ctrlTuesdayLabel" runat="server" Text="Вторник" EnableViewState="False">
                    </asp:Label>
                    <ac:TimeSpanView ID="ctrlTuesdayTS" runat="server" />
                </div>
                <div class="clearfix">
                    <asp:Label CssClass="descLbl" ID="ctrlWednesdayLabel" runat="server" Text="Среда" EnableViewState="False">
                    </asp:Label>
                    <ac:TimeSpanView ID="ctrlWednesdayTS" runat="server" />
                </div>
                <div class="clearfix">
                    <asp:Label CssClass="descLbl" ID="ctrlThursdayLabel" runat="server" Text="Четверг" EnableViewState="False">
                    </asp:Label>
                    <ac:TimeSpanView ID="ctrlThursdayTS" runat="server" />
                </div>
                <div class="clearfix">
                    <asp:Label CssClass="descLbl" ID="ctrlFridayLabel" runat="server" Text="Пятница" EnableViewState="False">
                    </asp:Label>
                    <ac:TimeSpanView ID="ctrlFridayTS" runat="server" />
                </div>
                <div class="clearfix">
                    <asp:Label CssClass="descLbl" ID="ctrlSaturdayLabel" runat="server" Text="Суббота" EnableViewState="False">
                    </asp:Label>
                    <ac:TimeSpanView ID="ctrlSaturdayTS" runat="server" />
                </div>
                <div class="clearfix">
                    <asp:Label CssClass="descLbl" ID="ctrlSundayLabel" runat="server" Text="Воскресенье" EnableViewState="False">
                    </asp:Label>
                    <ac:TimeSpanView ID="ctrlSundayTS" runat="server" />
                </div>

            </div>
<!-- autogenerated end -->
            <%-- Autogenerated section end [Controls] --%>
        </div>
    </div>
</asp:Content>
