//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Product_58826
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET.Business;
    using ICSSoft.STORMNET;
    using ICSSoft.STORMNET.Business.Audit;
    using ICSSoft.STORMNET.Business.Audit.Objects;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Семестр.
    /// </summary>
    // *** Start programmer edit section *** (Семестр CustomAttributes)

    // *** End programmer edit section *** (Семестр CustomAttributes)
    [BusinessServer("IIS.Product_58826.СеместрБС, Product_58826(BusinessServers)", ICSSoft.STORMNET.Business.DataServiceObjectEvents.OnAllEvents)]
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.@this)]
    [View("AuditView", new string[] {
            "Номер as \'Номер\'",
            "Начало as \'Начало\'",
            "Конец as \'Конец\'",
            "Актуальность as \'Актуальность\'"})]
    [View("СеместрE", new string[] {
            "Номер as \'№ семестра\'",
            "Начало as \'Начало\'",
            "Конец as \'Конец\'",
            "Актуальность"})]
    [View("СеместрL", new string[] {
            "Номер as \'Семестр № \'",
            "Начало as \'с \'",
            "Конец as \'по \'",
            "Актуальность"})]
    public class Семестр : ICSSoft.STORMNET.DataObject, IDataObjectWithAuditFields
    {
        
        private int fНомер;
        
        private System.DateTime fНачало;
        
        private System.DateTime fКонец;
        
        private bool fАктуальность = true;
        
        private System.Nullable<System.DateTime> fCreateTime;
        
        private string fCreator;
        
        private System.Nullable<System.DateTime> fEditTime;
        
        private string fEditor;
        
        // *** Start programmer edit section *** (Семестр CustomMembers)

        // *** End programmer edit section *** (Семестр CustomMembers)

        
        /// <summary>
        /// Номер.
        /// </summary>
        // *** Start programmer edit section *** (Семестр.Номер CustomAttributes)

        // *** End programmer edit section *** (Семестр.Номер CustomAttributes)
        [NotNull()]
        public virtual int Номер
        {
            get
            {
                // *** Start programmer edit section *** (Семестр.Номер Get start)

                // *** End programmer edit section *** (Семестр.Номер Get start)
                int result = this.fНомер;
                // *** Start programmer edit section *** (Семестр.Номер Get end)

                // *** End programmer edit section *** (Семестр.Номер Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Семестр.Номер Set start)

                // *** End programmer edit section *** (Семестр.Номер Set start)
                this.fНомер = value;
                // *** Start programmer edit section *** (Семестр.Номер Set end)

                // *** End programmer edit section *** (Семестр.Номер Set end)
            }
        }
        
        /// <summary>
        /// Начало.
        /// </summary>
        // *** Start programmer edit section *** (Семестр.Начало CustomAttributes)

        // *** End programmer edit section *** (Семестр.Начало CustomAttributes)
        [NotNull()]
        public virtual System.DateTime Начало
        {
            get
            {
                // *** Start programmer edit section *** (Семестр.Начало Get start)

                // *** End programmer edit section *** (Семестр.Начало Get start)
                System.DateTime result = this.fНачало;
                // *** Start programmer edit section *** (Семестр.Начало Get end)

                // *** End programmer edit section *** (Семестр.Начало Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Семестр.Начало Set start)

                // *** End programmer edit section *** (Семестр.Начало Set start)
                this.fНачало = value;
                // *** Start programmer edit section *** (Семестр.Начало Set end)

                // *** End programmer edit section *** (Семестр.Начало Set end)
            }
        }
        
        /// <summary>
        /// Конец.
        /// </summary>
        // *** Start programmer edit section *** (Семестр.Конец CustomAttributes)

        // *** End programmer edit section *** (Семестр.Конец CustomAttributes)
        [NotNull()]
        public virtual System.DateTime Конец
        {
            get
            {
                // *** Start programmer edit section *** (Семестр.Конец Get start)

                // *** End programmer edit section *** (Семестр.Конец Get start)
                System.DateTime result = this.fКонец;
                // *** Start programmer edit section *** (Семестр.Конец Get end)

                // *** End programmer edit section *** (Семестр.Конец Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Семестр.Конец Set start)

                // *** End programmer edit section *** (Семестр.Конец Set start)
                this.fКонец = value;
                // *** Start programmer edit section *** (Семестр.Конец Set end)

                // *** End programmer edit section *** (Семестр.Конец Set end)
            }
        }
        
        /// <summary>
        /// Актуальность.
        /// </summary>
        // *** Start programmer edit section *** (Семестр.Актуальность CustomAttributes)

        // *** End programmer edit section *** (Семестр.Актуальность CustomAttributes)
        public virtual bool Актуальность
        {
            get
            {
                // *** Start programmer edit section *** (Семестр.Актуальность Get start)

                // *** End programmer edit section *** (Семестр.Актуальность Get start)
                bool result = this.fАктуальность;
                // *** Start programmer edit section *** (Семестр.Актуальность Get end)

                // *** End programmer edit section *** (Семестр.Актуальность Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Семестр.Актуальность Set start)

                // *** End programmer edit section *** (Семестр.Актуальность Set start)
                this.fАктуальность = value;
                // *** Start programmer edit section *** (Семестр.Актуальность Set end)

                // *** End programmer edit section *** (Семестр.Актуальность Set end)
            }
        }
        
        /// <summary>
        /// Время создания объекта.
        /// </summary>
        // *** Start programmer edit section *** (Семестр.CreateTime CustomAttributes)

        // *** End programmer edit section *** (Семестр.CreateTime CustomAttributes)
        public virtual System.Nullable<System.DateTime> CreateTime
        {
            get
            {
                // *** Start programmer edit section *** (Семестр.CreateTime Get start)

                // *** End programmer edit section *** (Семестр.CreateTime Get start)
                System.Nullable<System.DateTime> result = this.fCreateTime;
                // *** Start programmer edit section *** (Семестр.CreateTime Get end)

                // *** End programmer edit section *** (Семестр.CreateTime Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Семестр.CreateTime Set start)

                // *** End programmer edit section *** (Семестр.CreateTime Set start)
                this.fCreateTime = value;
                // *** Start programmer edit section *** (Семестр.CreateTime Set end)

                // *** End programmer edit section *** (Семестр.CreateTime Set end)
            }
        }
        
        /// <summary>
        /// Создатель объекта.
        /// </summary>
        // *** Start programmer edit section *** (Семестр.Creator CustomAttributes)

        // *** End programmer edit section *** (Семестр.Creator CustomAttributes)
        [StrLen(255)]
        public virtual string Creator
        {
            get
            {
                // *** Start programmer edit section *** (Семестр.Creator Get start)

                // *** End programmer edit section *** (Семестр.Creator Get start)
                string result = this.fCreator;
                // *** Start programmer edit section *** (Семестр.Creator Get end)

                // *** End programmer edit section *** (Семестр.Creator Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Семестр.Creator Set start)

                // *** End programmer edit section *** (Семестр.Creator Set start)
                this.fCreator = value;
                // *** Start programmer edit section *** (Семестр.Creator Set end)

                // *** End programmer edit section *** (Семестр.Creator Set end)
            }
        }
        
        /// <summary>
        /// Время последнего редактирования объекта.
        /// </summary>
        // *** Start programmer edit section *** (Семестр.EditTime CustomAttributes)

        // *** End programmer edit section *** (Семестр.EditTime CustomAttributes)
        public virtual System.Nullable<System.DateTime> EditTime
        {
            get
            {
                // *** Start programmer edit section *** (Семестр.EditTime Get start)

                // *** End programmer edit section *** (Семестр.EditTime Get start)
                System.Nullable<System.DateTime> result = this.fEditTime;
                // *** Start programmer edit section *** (Семестр.EditTime Get end)

                // *** End programmer edit section *** (Семестр.EditTime Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Семестр.EditTime Set start)

                // *** End programmer edit section *** (Семестр.EditTime Set start)
                this.fEditTime = value;
                // *** Start programmer edit section *** (Семестр.EditTime Set end)

                // *** End programmer edit section *** (Семестр.EditTime Set end)
            }
        }
        
        /// <summary>
        /// Последний редактор объекта.
        /// </summary>
        // *** Start programmer edit section *** (Семестр.Editor CustomAttributes)

        // *** End programmer edit section *** (Семестр.Editor CustomAttributes)
        [StrLen(255)]
        public virtual string Editor
        {
            get
            {
                // *** Start programmer edit section *** (Семестр.Editor Get start)

                // *** End programmer edit section *** (Семестр.Editor Get start)
                string result = this.fEditor;
                // *** Start programmer edit section *** (Семестр.Editor Get end)

                // *** End programmer edit section *** (Семестр.Editor Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Семестр.Editor Set start)

                // *** End programmer edit section *** (Семестр.Editor Set start)
                this.fEditor = value;
                // *** Start programmer edit section *** (Семестр.Editor Set end)

                // *** End programmer edit section *** (Семестр.Editor Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "AuditView" view.
            /// </summary>
            public static ICSSoft.STORMNET.View AuditView
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("AuditView", typeof(IIS.Product_58826.Семестр));
                }
            }
            
            /// <summary>
            /// "СеместрE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СеместрE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СеместрE", typeof(IIS.Product_58826.Семестр));
                }
            }
            
            /// <summary>
            /// "СеместрL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СеместрL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СеместрL", typeof(IIS.Product_58826.Семестр));
                }
            }
        }
        
        /// <summary>
        /// Audit class settings.
        /// </summary>
        public class AuditSettings
        {
            
            /// <summary>
            /// Включён ли аудит для класса.
            /// </summary>
            public static bool AuditEnabled = true;
            
            /// <summary>
            /// Использовать имя представления для аудита по умолчанию.
            /// </summary>
            public static bool UseDefaultView = false;
            
            /// <summary>
            /// Включён ли аудит операции чтения.
            /// </summary>
            public static bool SelectAudit = false;
            
            /// <summary>
            /// Имя представления для аудирования операции чтения.
            /// </summary>
            public static string SelectAuditViewName = "AuditView";
            
            /// <summary>
            /// Включён ли аудит операции создания.
            /// </summary>
            public static bool InsertAudit = true;
            
            /// <summary>
            /// Имя представления для аудирования операции создания.
            /// </summary>
            public static string InsertAuditViewName = "AuditView";
            
            /// <summary>
            /// Включён ли аудит операции изменения.
            /// </summary>
            public static bool UpdateAudit = true;
            
            /// <summary>
            /// Имя представления для аудирования операции изменения.
            /// </summary>
            public static string UpdateAuditViewName = "AuditView";
            
            /// <summary>
            /// Включён ли аудит операции удаления.
            /// </summary>
            public static bool DeleteAudit = true;
            
            /// <summary>
            /// Имя представления для аудирования операции удаления.
            /// </summary>
            public static string DeleteAuditViewName = "AuditView";
            
            /// <summary>
            /// Путь к форме просмотра результатов аудита.
            /// </summary>
            public static string FormUrl = "";
            
            /// <summary>
            /// Режим записи данных аудита (синхронный или асинхронный).
            /// </summary>
            public static ICSSoft.STORMNET.Business.Audit.Objects.tWriteMode WriteMode = ICSSoft.STORMNET.Business.Audit.Objects.tWriteMode.Synchronous;
            
            /// <summary>
            /// Максимальная длина сохраняемого значения поля (если 0, то строка обрезаться не будет).
            /// </summary>
            public static int PrunningLength = 0;
            
            /// <summary>
            /// Показывать ли пользователям в изменениях первичные ключи.
            /// </summary>
            public static bool ShowPrimaryKey = false;
            
            /// <summary>
            /// Сохранять ли старое значение.
            /// </summary>
            public static bool KeepOldValue = true;
            
            /// <summary>
            /// Сжимать ли сохраняемые значения.
            /// </summary>
            public static bool Compress = false;
            
            /// <summary>
            /// Сохранять ли все значения атрибутов, а не только изменяемые.
            /// </summary>
            public static bool KeepAllValues = false;
        }
    }
}
