<%--flexberryautogenerated="true"--%>
<%@ Page Language="C#" MasterPageFile="~/Site1.Master" AutoEventWireup="true" CodeBehind="ExceptionDayL.aspx.cs" Inherits="IIS.BusinessCalendar.ExceptionDayL" %>
<%@ Import namespace="NewPlatform.Flexberry.Web.Page" %>
<%@ Register TagPrefix="ac" TagName="CalendarView" Src="~/Controls/Calendar/CalendarView.ascx" %>
<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <div class="<%= Constants.FormCssClass %> <%= Constants.ListFormCssClass %>">
        <h2 class="<%= Constants.FormHeaderCssClass %> <%= Constants.ListFormHeaderCssClass %>">Дни исключения</h2>
        <div class="<%= Constants.FormControlsCssClass %> <%= Constants.ListFormControlsCssClass %>">
            <div class="marginStandart">
                <ac:CalendarView ID="ctrlCalendarView" runat="server" />
            </div>
            <ac:WebObjectListView ID="WebObjectListView1" runat="server" Visible="true" 
                OnObjectsDeleted="WebObjectListView1_ObjectsDeleted" 
                OnObjectAdding="WebObjectListView1_ObjectAdding" 
                OnObjectEditing="WebObjectListView1_ObjectEditing"/>
        </div>
    </div>
    
    <script>
        var WolVID = <%= WebObjectListView1.ClientID%>;
        function closeEditForm(){
            $('#<%= ctrlCalendarView.ClientID%>').CalendarView('closeEditForm');
            window.location.reload();
        };
    </script>
</asp:Content>

