//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeploCorp.TeploUchet
{
    using ICSSoft.STORMNET;
    using ICSSoft.STORMNET.Business;
    using ICSSoft.STORMNET.Business.LINQProvider;
    using System.Linq;
    using System;
    
    using System.Xml;


    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// УдалениеУчастка.
    /// </summary>
    // *** Start programmer edit section *** (УдалениеУчастка CustomAttributes)

    // *** End programmer edit section *** (УдалениеУчастка CustomAttributes)
    [ICSSoft.STORMNET.AccessType(ICSSoft.STORMNET.AccessType.none)]
    public class УдалениеУчастка : ICSSoft.STORMNET.Business.BusinessServer
    {
        
        // *** Start programmer edit section *** (УдалениеУчастка CustomMembers)

        // *** End programmer edit section *** (УдалениеУчастка CustomMembers)

        
        // *** Start programmer edit section *** (OnUpdateУчастокСети CustomAttributes)

        // *** End programmer edit section *** (OnUpdateУчастокСети CustomAttributes)
        public virtual ICSSoft.STORMNET.DataObject[] OnUpdateУчастокСети(TeploCorp.TeploUchet.УчастокСети UpdatedObject)
        {
            // *** Start programmer edit section *** (OnUpdateУчастокСети)
            //ставим флаг удален 
            if (UpdatedObject.GetStatus() == ObjectStatus.Deleted)
            {
                // Не дадим объекту удалиться, но выставим флаг Актуальности.
                DataService.LoadObject(UpdatedObject);
                UpdatedObject.SetStatus(ObjectStatus.Altered);
                UpdatedObject.Актуален = false;

                var ds = (SQLDataService)DataServiceProvider.DataService;
                var delobjects = ds.Query<УчастокСети>(УчастокСети.Views.УчастокСетиE).Where(x => x.Объект.__PrimaryKey == UpdatedObject.__PrimaryKey);
                foreach (var i in delobjects)
                {
                    i.SetStatus(ObjectStatus.Deleted);
                }
                return delobjects.ToArray();
            }
            return new ICSSoft.STORMNET.DataObject[0];
            // *** End programmer edit section *** (OnUpdateУчастокСети)
        }
    }
}
