//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.BusinessCalendar
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Определение дня-исключения.
    /// </summary>
    // *** Start programmer edit section *** (WorkTimeDefinition CustomAttributes)

    // *** End programmer edit section *** (WorkTimeDefinition CustomAttributes)
    [AutoAltered()]
    [Caption("Определение дня-исключения")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("Flexberry_WorkTimeDefinitionE", new string[] {
            "Name as \'Название\'"})]
    [AssociatedDetailViewAttribute("Flexberry_WorkTimeDefinitionE", "WorkTimeSpan", "Flexberry_WorkTimeSpanE", true, "", "Work time span", true, new string[] {
            ""})]
    [View("Flexberry_WorkTimeDefinitionL", new string[] {
            "Name as \'Название\'"})]
    public class WorkTimeDefinition : ICSSoft.STORMNET.DataObject
    {
        
        private string fName;
        
        private IIS.BusinessCalendar.DetailArrayOfWorkTimeSpan fWorkTimeSpan;
        
        // *** Start programmer edit section *** (WorkTimeDefinition CustomMembers)

        // *** End programmer edit section *** (WorkTimeDefinition CustomMembers)

        
        /// <summary>
        /// Название.
        /// </summary>
        // *** Start programmer edit section *** (WorkTimeDefinition.Name CustomAttributes)

        // *** End programmer edit section *** (WorkTimeDefinition.Name CustomAttributes)
        [StrLen(255)]
        public virtual string Name
        {
            get
            {
                // *** Start programmer edit section *** (WorkTimeDefinition.Name Get start)

                // *** End programmer edit section *** (WorkTimeDefinition.Name Get start)
                string result = this.fName;
                // *** Start programmer edit section *** (WorkTimeDefinition.Name Get end)

                // *** End programmer edit section *** (WorkTimeDefinition.Name Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (WorkTimeDefinition.Name Set start)

                // *** End programmer edit section *** (WorkTimeDefinition.Name Set start)
                this.fName = value;
                // *** Start programmer edit section *** (WorkTimeDefinition.Name Set end)

                // *** End programmer edit section *** (WorkTimeDefinition.Name Set end)
            }
        }
        
        /// <summary>
        /// Определение дня-исключения.
        /// </summary>
        // *** Start programmer edit section *** (WorkTimeDefinition.WorkTimeSpan CustomAttributes)

        // *** End programmer edit section *** (WorkTimeDefinition.WorkTimeSpan CustomAttributes)
        public virtual IIS.BusinessCalendar.DetailArrayOfWorkTimeSpan WorkTimeSpan
        {
            get
            {
                // *** Start programmer edit section *** (WorkTimeDefinition.WorkTimeSpan Get start)

                // *** End programmer edit section *** (WorkTimeDefinition.WorkTimeSpan Get start)
                if ((this.fWorkTimeSpan == null))
                {
                    this.fWorkTimeSpan = new IIS.BusinessCalendar.DetailArrayOfWorkTimeSpan(this);
                }
                IIS.BusinessCalendar.DetailArrayOfWorkTimeSpan result = this.fWorkTimeSpan;
                // *** Start programmer edit section *** (WorkTimeDefinition.WorkTimeSpan Get end)

                // *** End programmer edit section *** (WorkTimeDefinition.WorkTimeSpan Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (WorkTimeDefinition.WorkTimeSpan Set start)

                // *** End programmer edit section *** (WorkTimeDefinition.WorkTimeSpan Set start)
                this.fWorkTimeSpan = value;
                // *** Start programmer edit section *** (WorkTimeDefinition.WorkTimeSpan Set end)

                // *** End programmer edit section *** (WorkTimeDefinition.WorkTimeSpan Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "Flexberry_WorkTimeDefinitionE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View Flexberry_WorkTimeDefinitionE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("Flexberry_WorkTimeDefinitionE", typeof(IIS.BusinessCalendar.WorkTimeDefinition));
                }
            }
            
            /// <summary>
            /// "Flexberry_WorkTimeDefinitionL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View Flexberry_WorkTimeDefinitionL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("Flexberry_WorkTimeDefinitionL", typeof(IIS.BusinessCalendar.WorkTimeDefinition));
                }
            }
        }
    }
}
