/*flexberryautogenerated="true"*/
namespace IIS.Product_58826
{
    using System;
    using ICSSoft.STORMNET.Web.Controls;

    using Resources;

    public partial class МодульL : BaseListForm<Модуль>
    {
        /// <summary>
        /// Конструктор без параметров,
        /// инициализирует свойства, соответствующие конкретной форме.
        /// </summary>
        public МодульL() : base(Модуль.Views.МодульL)
        {
            EditPage = МодульE.FormPath;
        }
                
        /// <summary>
        /// Путь до формы.
        /// </summary>
        public static string FormPath
        {
            get { return "~/forms/Modul/ModulL.aspx"; }
        }

        /// <summary>
        /// Вызывается самым первым в Page_Load.
        /// </summary>
        protected override void Preload()
        {
        }

        /// <summary>
        /// Вызывается самым последним в Page_Load.
        /// </summary>
        protected override void Postload()
        {
        }
    }
}
