//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewPlatform.RecordBook
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Группа.
    /// </summary>
    // *** Start programmer edit section *** (Группа CustomAttributes)

    // *** End programmer edit section *** (Группа CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ГруппаE", new string[] {
            "Название as \'Название\'",
            "Факультет as \'Факультет\'",
            "Факультет.Название as \'Название\'",
            "Староста as \'Староста\'",
            "Староста.Фамилия as \'Фамилия\'"})]
    [AssociatedDetailViewAttribute("ГруппаE", "Студенты", "СтудентE", true, "", "Студенты", true, new string[] {
            ""})]
    [View("ГруппаL", new string[] {
            "Название as \'Название\'",
            "Факультет.Название as \'Название\'",
            "Староста.Фамилия as \'Фамилия\'"})]
    public class Группа : ICSSoft.STORMNET.DataObject
    {
        
        private string fНазвание;
        
        private NewPlatform.RecordBook.Факультет fФакультет;
        
        private NewPlatform.RecordBook.Студент fСтароста;
        
        private NewPlatform.RecordBook.DetailArrayOfСтудент fСтуденты;
        
        // *** Start programmer edit section *** (Группа CustomMembers)

        // *** End programmer edit section *** (Группа CustomMembers)

        
        /// <summary>
        /// Название.
        /// </summary>
        // *** Start programmer edit section *** (Группа.Название CustomAttributes)

        // *** End programmer edit section *** (Группа.Название CustomAttributes)
        [StrLen(255)]
        public virtual string Название
        {
            get
            {
                // *** Start programmer edit section *** (Группа.Название Get start)

                // *** End programmer edit section *** (Группа.Название Get start)
                string result = this.fНазвание;
                // *** Start programmer edit section *** (Группа.Название Get end)

                // *** End programmer edit section *** (Группа.Название Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Группа.Название Set start)

                // *** End programmer edit section *** (Группа.Название Set start)
                this.fНазвание = value;
                // *** Start programmer edit section *** (Группа.Название Set end)

                // *** End programmer edit section *** (Группа.Название Set end)
            }
        }
        
        /// <summary>
        /// Группа.
        /// </summary>
        // *** Start programmer edit section *** (Группа.Факультет CustomAttributes)

        // *** End programmer edit section *** (Группа.Факультет CustomAttributes)
        [PropertyStorage(new string[] {
                "Факультет"})]
        [NotNull()]
        public virtual NewPlatform.RecordBook.Факультет Факультет
        {
            get
            {
                // *** Start programmer edit section *** (Группа.Факультет Get start)

                // *** End programmer edit section *** (Группа.Факультет Get start)
                NewPlatform.RecordBook.Факультет result = this.fФакультет;
                // *** Start programmer edit section *** (Группа.Факультет Get end)

                // *** End programmer edit section *** (Группа.Факультет Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Группа.Факультет Set start)

                // *** End programmer edit section *** (Группа.Факультет Set start)
                this.fФакультет = value;
                // *** Start programmer edit section *** (Группа.Факультет Set end)

                // *** End programmer edit section *** (Группа.Факультет Set end)
            }
        }
        
        /// <summary>
        /// Группа.
        /// </summary>
        // *** Start programmer edit section *** (Группа.Староста CustomAttributes)

        // *** End programmer edit section *** (Группа.Староста CustomAttributes)
        public virtual NewPlatform.RecordBook.Студент Староста
        {
            get
            {
                // *** Start programmer edit section *** (Группа.Староста Get start)

                // *** End programmer edit section *** (Группа.Староста Get start)
                NewPlatform.RecordBook.Студент result = this.fСтароста;
                // *** Start programmer edit section *** (Группа.Староста Get end)

                // *** End programmer edit section *** (Группа.Староста Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Группа.Староста Set start)

                // *** End programmer edit section *** (Группа.Староста Set start)
                this.fСтароста = value;
                // *** Start programmer edit section *** (Группа.Староста Set end)

                // *** End programmer edit section *** (Группа.Староста Set end)
            }
        }
        
        /// <summary>
        /// Группа.
        /// </summary>
        // *** Start programmer edit section *** (Группа.Студенты CustomAttributes)

        // *** End programmer edit section *** (Группа.Студенты CustomAttributes)
        public virtual NewPlatform.RecordBook.DetailArrayOfСтудент Студенты
        {
            get
            {
                // *** Start programmer edit section *** (Группа.Студенты Get start)

                // *** End programmer edit section *** (Группа.Студенты Get start)
                if ((this.fСтуденты == null))
                {
                    this.fСтуденты = new NewPlatform.RecordBook.DetailArrayOfСтудент(this);
                }
                NewPlatform.RecordBook.DetailArrayOfСтудент result = this.fСтуденты;
                // *** Start programmer edit section *** (Группа.Студенты Get end)

                // *** End programmer edit section *** (Группа.Студенты Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Группа.Студенты Set start)

                // *** End programmer edit section *** (Группа.Студенты Set start)
                this.fСтуденты = value;
                // *** Start programmer edit section *** (Группа.Студенты Set end)

                // *** End programmer edit section *** (Группа.Студенты Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ГруппаE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ГруппаE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ГруппаE", typeof(NewPlatform.RecordBook.Группа));
                }
            }
            
            /// <summary>
            /// "ГруппаL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ГруппаL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ГруппаL", typeof(NewPlatform.RecordBook.Группа));
                }
            }
        }
    }
}
