/*flexberryautogenerated="true"*/
namespace NewPlatform.RecordBookBL
{
    using System;
    using ICSSoft.STORMNET.Web.Controls;

    using Resources;

    public partial class FormForGroup : BaseListForm<Группа>
    {
        /// <summary>
        /// Конструктор без параметров,
        /// инициализирует свойства, соответствующие конкретной форме.
        /// </summary>
        public FormForGroup() : base(Группа.Views.ГруппаL)
        {
            EditPage = ГруппаE.FormPath;
        }
                
        /// <summary>
        /// Путь до формы.
        /// </summary>
        public static string FormPath
        {
            get { return "~/forms/Gruppa/FormForGroup.aspx"; }
        }

        /// <summary>
        /// Вызывается самым первым в Page_Load.
        /// </summary>
        protected override void Preload()
        {
        }

        /// <summary>
        /// Вызывается самым последним в Page_Load.
        /// </summary>
        protected override void Postload()
        {
        }
    }
}
