//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Product_58826
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Организация.
    /// </summary>
    // *** Start programmer edit section *** (Организация CustomAttributes)

    // *** End programmer edit section *** (Организация CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ОрганизацияE", new string[] {
            "Название as \'Организация\'",
            "Описание as \'Описание\'"})]
    [View("ОрганизацияL", new string[] {
            "Название as \'Организация \'",
            "Описание as \'Описание \'"})]
    public class Организация : ICSSoft.STORMNET.DataObject
    {
        
        private string fНазвание;
        
        private string fОписание;
        
        // *** Start programmer edit section *** (Организация CustomMembers)

        // *** End programmer edit section *** (Организация CustomMembers)

        
        /// <summary>
        /// Название.
        /// </summary>
        // *** Start programmer edit section *** (Организация.Название CustomAttributes)

        // *** End programmer edit section *** (Организация.Название CustomAttributes)
        [StrLen(255)]
        [NotNull()]
        public virtual string Название
        {
            get
            {
                // *** Start programmer edit section *** (Организация.Название Get start)

                // *** End programmer edit section *** (Организация.Название Get start)
                string result = this.fНазвание;
                // *** Start programmer edit section *** (Организация.Название Get end)

                // *** End programmer edit section *** (Организация.Название Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Организация.Название Set start)

                // *** End programmer edit section *** (Организация.Название Set start)
                this.fНазвание = value;
                // *** Start programmer edit section *** (Организация.Название Set end)

                // *** End programmer edit section *** (Организация.Название Set end)
            }
        }
        
        /// <summary>
        /// Описание.
        /// </summary>
        // *** Start programmer edit section *** (Организация.Описание CustomAttributes)

        // *** End programmer edit section *** (Организация.Описание CustomAttributes)
        [StrLen(255)]
        [NotNull()]
        public virtual string Описание
        {
            get
            {
                // *** Start programmer edit section *** (Организация.Описание Get start)

                // *** End programmer edit section *** (Организация.Описание Get start)
                string result = this.fОписание;
                // *** Start programmer edit section *** (Организация.Описание Get end)

                // *** End programmer edit section *** (Организация.Описание Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Организация.Описание Set start)

                // *** End programmer edit section *** (Организация.Описание Set start)
                this.fОписание = value;
                // *** Start programmer edit section *** (Организация.Описание Set end)

                // *** End programmer edit section *** (Организация.Описание Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ОрганизацияE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ОрганизацияE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ОрганизацияE", typeof(IIS.Product_58826.Организация));
                }
            }
            
            /// <summary>
            /// "ОрганизацияL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ОрганизацияL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ОрганизацияL", typeof(IIS.Product_58826.Организация));
                }
            }
        }
    }
}
