//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Product_58826
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET.Business;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Семестр.
    /// </summary>
    // *** Start programmer edit section *** (Семестр CustomAttributes)

    // *** End programmer edit section *** (Семестр CustomAttributes)
    [BusinessServer("IIS.Product_58826.СеместрБС, Product_58826(BusinessServers)", ICSSoft.STORMNET.Business.DataServiceObjectEvents.OnAllEvents)]
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("СеместрE", new string[] {
            "Номер as \'№ семестра\'",
            "Начало as \'Начало\'",
            "Конец as \'Конец\'",
            "Актуальность"})]
    [View("СеместрL", new string[] {
            "Номер as \'Семестр № \'",
            "Начало as \'с \'",
            "Конец as \'по \'",
            "Актуальность"})]
    public class Семестр : ICSSoft.STORMNET.DataObject
    {
        
        private int fНомер;
        
        private System.DateTime fНачало;
        
        private System.DateTime fКонец;
        
        private bool fАктуальность = true;
        
        // *** Start programmer edit section *** (Семестр CustomMembers)

        // *** End programmer edit section *** (Семестр CustomMembers)

        
        /// <summary>
        /// Номер.
        /// </summary>
        // *** Start programmer edit section *** (Семестр.Номер CustomAttributes)

        // *** End programmer edit section *** (Семестр.Номер CustomAttributes)
        [NotNull()]
        public virtual int Номер
        {
            get
            {
                // *** Start programmer edit section *** (Семестр.Номер Get start)

                // *** End programmer edit section *** (Семестр.Номер Get start)
                int result = this.fНомер;
                // *** Start programmer edit section *** (Семестр.Номер Get end)

                // *** End programmer edit section *** (Семестр.Номер Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Семестр.Номер Set start)

                // *** End programmer edit section *** (Семестр.Номер Set start)
                this.fНомер = value;
                // *** Start programmer edit section *** (Семестр.Номер Set end)

                // *** End programmer edit section *** (Семестр.Номер Set end)
            }
        }
        
        /// <summary>
        /// Начало.
        /// </summary>
        // *** Start programmer edit section *** (Семестр.Начало CustomAttributes)

        // *** End programmer edit section *** (Семестр.Начало CustomAttributes)
        [NotNull()]
        public virtual System.DateTime Начало
        {
            get
            {
                // *** Start programmer edit section *** (Семестр.Начало Get start)

                // *** End programmer edit section *** (Семестр.Начало Get start)
                System.DateTime result = this.fНачало;
                // *** Start programmer edit section *** (Семестр.Начало Get end)

                // *** End programmer edit section *** (Семестр.Начало Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Семестр.Начало Set start)

                // *** End programmer edit section *** (Семестр.Начало Set start)
                this.fНачало = value;
                // *** Start programmer edit section *** (Семестр.Начало Set end)

                // *** End programmer edit section *** (Семестр.Начало Set end)
            }
        }
        
        /// <summary>
        /// Конец.
        /// </summary>
        // *** Start programmer edit section *** (Семестр.Конец CustomAttributes)

        // *** End programmer edit section *** (Семестр.Конец CustomAttributes)
        [NotNull()]
        public virtual System.DateTime Конец
        {
            get
            {
                // *** Start programmer edit section *** (Семестр.Конец Get start)

                // *** End programmer edit section *** (Семестр.Конец Get start)
                System.DateTime result = this.fКонец;
                // *** Start programmer edit section *** (Семестр.Конец Get end)

                // *** End programmer edit section *** (Семестр.Конец Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Семестр.Конец Set start)

                // *** End programmer edit section *** (Семестр.Конец Set start)
                this.fКонец = value;
                // *** Start programmer edit section *** (Семестр.Конец Set end)

                // *** End programmer edit section *** (Семестр.Конец Set end)
            }
        }
        
        /// <summary>
        /// Актуальность.
        /// </summary>
        // *** Start programmer edit section *** (Семестр.Актуальность CustomAttributes)

        // *** End programmer edit section *** (Семестр.Актуальность CustomAttributes)
        public virtual bool Актуальность
        {
            get
            {
                // *** Start programmer edit section *** (Семестр.Актуальность Get start)

                // *** End programmer edit section *** (Семестр.Актуальность Get start)
                bool result = this.fАктуальность;
                // *** Start programmer edit section *** (Семестр.Актуальность Get end)

                // *** End programmer edit section *** (Семестр.Актуальность Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Семестр.Актуальность Set start)

                // *** End programmer edit section *** (Семестр.Актуальность Set start)
                this.fАктуальность = value;
                // *** Start programmer edit section *** (Семестр.Актуальность Set end)

                // *** End programmer edit section *** (Семестр.Актуальность Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "СеместрE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СеместрE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СеместрE", typeof(IIS.Product_58826.Семестр));
                }
            }
            
            /// <summary>
            /// "СеместрL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СеместрL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СеместрL", typeof(IIS.Product_58826.Семестр));
                }
            }
        }
    }
}
