//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeploCorp.TeploUchet
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET.Business;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Район.
    /// </summary>
    // *** Start programmer edit section *** (Район CustomAttributes)

    // *** End programmer edit section *** (Район CustomAttributes)
    [BusinessServer("TeploCorp.TeploUchet.УдалениеРайона, TeploUchet(BusinessServers)", ICSSoft.STORMNET.Business.DataServiceObjectEvents.OnAllEvents)]
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("AuditView", new string[] {
            "Название as \'Название\'"})]
    [View("РайонE", new string[] {
            "Название as \'Название\'",
            "Актуален"})]
    [View("РайонL", new string[] {
            "Название as \'Название\'",
            "Актуален"})]
    public class Район : ICSSoft.STORMNET.DataObject
    {
        
        private string fНазвание;
        
        private System.Nullable<System.DateTime> fCreateTime;
        
        private string fCreator;
        
        private System.Nullable<System.DateTime> fEditTime;
        
        private string fEditor;
        
        private bool fАктуален = true;
        
        // *** Start programmer edit section *** (Район CustomMembers)

        // *** End programmer edit section *** (Район CustomMembers)

        
        /// <summary>
        /// Название.
        /// </summary>
        // *** Start programmer edit section *** (Район.Название CustomAttributes)

        // *** End programmer edit section *** (Район.Название CustomAttributes)
        [StrLen(255)]
        [NotNull()]
        public virtual string Название
        {
            get
            {
                // *** Start programmer edit section *** (Район.Название Get start)

                // *** End programmer edit section *** (Район.Название Get start)
                string result = this.fНазвание;
                // *** Start programmer edit section *** (Район.Название Get end)

                // *** End programmer edit section *** (Район.Название Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Район.Название Set start)

                // *** End programmer edit section *** (Район.Название Set start)
                this.fНазвание = value;
                // *** Start programmer edit section *** (Район.Название Set end)

                // *** End programmer edit section *** (Район.Название Set end)
            }
        }
        
        /// <summary>
        /// Время создания объекта.
        /// </summary>
        // *** Start programmer edit section *** (Район.CreateTime CustomAttributes)

        // *** End programmer edit section *** (Район.CreateTime CustomAttributes)
        public virtual System.Nullable<System.DateTime> CreateTime
        {
            get
            {
                // *** Start programmer edit section *** (Район.CreateTime Get start)

                // *** End programmer edit section *** (Район.CreateTime Get start)
                System.Nullable<System.DateTime> result = this.fCreateTime;
                // *** Start programmer edit section *** (Район.CreateTime Get end)

                // *** End programmer edit section *** (Район.CreateTime Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Район.CreateTime Set start)

                // *** End programmer edit section *** (Район.CreateTime Set start)
                this.fCreateTime = value;
                // *** Start programmer edit section *** (Район.CreateTime Set end)

                // *** End programmer edit section *** (Район.CreateTime Set end)
            }
        }
        
        /// <summary>
        /// Создатель объекта.
        /// </summary>
        // *** Start programmer edit section *** (Район.Creator CustomAttributes)

        // *** End programmer edit section *** (Район.Creator CustomAttributes)
        [StrLen(255)]
        public virtual string Creator
        {
            get
            {
                // *** Start programmer edit section *** (Район.Creator Get start)

                // *** End programmer edit section *** (Район.Creator Get start)
                string result = this.fCreator;
                // *** Start programmer edit section *** (Район.Creator Get end)

                // *** End programmer edit section *** (Район.Creator Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Район.Creator Set start)

                // *** End programmer edit section *** (Район.Creator Set start)
                this.fCreator = value;
                // *** Start programmer edit section *** (Район.Creator Set end)

                // *** End programmer edit section *** (Район.Creator Set end)
            }
        }
        
        /// <summary>
        /// Время последнего редактирования объекта.
        /// </summary>
        // *** Start programmer edit section *** (Район.EditTime CustomAttributes)

        // *** End programmer edit section *** (Район.EditTime CustomAttributes)
        public virtual System.Nullable<System.DateTime> EditTime
        {
            get
            {
                // *** Start programmer edit section *** (Район.EditTime Get start)

                // *** End programmer edit section *** (Район.EditTime Get start)
                System.Nullable<System.DateTime> result = this.fEditTime;
                // *** Start programmer edit section *** (Район.EditTime Get end)

                // *** End programmer edit section *** (Район.EditTime Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Район.EditTime Set start)

                // *** End programmer edit section *** (Район.EditTime Set start)
                this.fEditTime = value;
                // *** Start programmer edit section *** (Район.EditTime Set end)

                // *** End programmer edit section *** (Район.EditTime Set end)
            }
        }
        
        /// <summary>
        /// Последний редактор объекта.
        /// </summary>
        // *** Start programmer edit section *** (Район.Editor CustomAttributes)

        // *** End programmer edit section *** (Район.Editor CustomAttributes)
        [StrLen(255)]
        public virtual string Editor
        {
            get
            {
                // *** Start programmer edit section *** (Район.Editor Get start)

                // *** End programmer edit section *** (Район.Editor Get start)
                string result = this.fEditor;
                // *** Start programmer edit section *** (Район.Editor Get end)

                // *** End programmer edit section *** (Район.Editor Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Район.Editor Set start)

                // *** End programmer edit section *** (Район.Editor Set start)
                this.fEditor = value;
                // *** Start programmer edit section *** (Район.Editor Set end)

                // *** End programmer edit section *** (Район.Editor Set end)
            }
        }
        
        /// <summary>
        /// Актуален.
        /// </summary>
        // *** Start programmer edit section *** (Район.Актуален CustomAttributes)

        // *** End programmer edit section *** (Район.Актуален CustomAttributes)
        public virtual bool Актуален
        {
            get
            {
                // *** Start programmer edit section *** (Район.Актуален Get start)

                // *** End programmer edit section *** (Район.Актуален Get start)
                bool result = this.fАктуален;
                // *** Start programmer edit section *** (Район.Актуален Get end)

                // *** End programmer edit section *** (Район.Актуален Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Район.Актуален Set start)

                // *** End programmer edit section *** (Район.Актуален Set start)
                this.fАктуален = value;
                // *** Start programmer edit section *** (Район.Актуален Set end)

                // *** End programmer edit section *** (Район.Актуален Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "AuditView" view.
            /// </summary>
            public static ICSSoft.STORMNET.View AuditView
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("AuditView", typeof(TeploCorp.TeploUchet.Район));
                }
            }
            
            /// <summary>
            /// "РайонE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View РайонE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("РайонE", typeof(TeploCorp.TeploUchet.Район));
                }
            }
            
            /// <summary>
            /// "РайонL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View РайонL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("РайонL", typeof(TeploCorp.TeploUchet.Район));
                }
            }
        }
    }
}
